package equivalent;

import org.junit.jupiter.api.Test;

import static equivalent.ClonePairGeneratedTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair8852Method1Test {

    private final ClonePair8852 subject = new ClonePair8852();

    @Test
    void method1Case01() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.NullPointerException.class, () -> subject.method1(null, 1, 1));
    }

    @Test
    void method1Case02() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbQqzzF/gGCFTgAgAAeHAAAAABAA==", subject.method1(new byte[]{}, 1, 1));
    }

    @Test
    void method1Case03() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbQqzzF/gGCFTgAgAAeHAAAAABAQ==", subject.method1(new byte[]{0, 1, 2}, 1, 1));
    }

    @Test
    void method1Case04() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.ArrayIndexOutOfBoundsException.class, () -> subject.method1(new byte[]{}, -1, 1));
    }

    @Test
    void method1Case05() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.NegativeArraySizeException.class, () -> subject.method1(new byte[]{}, 1, -1));
    }

}
