package equivalent;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

class ClonePair4134DifferenceFindingTest {

    private final ClonePair4134 subject = new ClonePair4134();

    /**
     * Generated by Codex (GPT-5.5).
     */
    @Test
    void methodsReturnDifferentListImplementationsForMissingBaseList() {
        List<String> additionsForMethod1 = new LinkedList<>(List.of("same"));
        List<String> additionsForMethod2 = new LinkedList<>(List.of("same"));

        List result1 = subject.method1(null, additionsForMethod1);
        List result2 = subject.method2(null, additionsForMethod2);

        assertEquals(List.of("same"), result1);
        assertEquals(List.of("same"), result2);
        assertEquals(ArrayList.class, result1.getClass());
        assertEquals(LinkedList.class, result2.getClass());
        assertNotEquals(result1.getClass(), result2.getClass());
    }
}
