package equivalent;

import org.junit.jupiter.api.Test;

import static equivalent.ClonePairDifferenceTestSupport.*;

class ClonePair9041DifferenceTest {

    private final ClonePair9041 subject = new ClonePair9041();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXNyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAAAB", subject.method1(-1));
        assertThrowsByName("java.lang.AssertionError", () -> subject.method2(-1));
    }
}
