package equivalent;

import org.junit.jupiter.api.Test;

import static equivalent.ClonePairGeneratedTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair5842Method2Test {

    private final ClonePair5842 subject = new ClonePair5842();

    @Test
    void method2Case01() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.ArrayIndexOutOfBoundsException.class, () -> subject.method2(new byte[]{}, 1, new byte[]{}, 1, 1));
    }

    @Test
    void method2Case02() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXNyABFqYXZhLmxhbmcuQm9vbGVhbs0gcoDVnPruAgABWgAFdmFsdWV4cAE=", subject.method2(new byte[]{}, 1, new byte[]{}, 1, -1));
    }

    @Test
    void method2Case03() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXNyABFqYXZhLmxhbmcuQm9vbGVhbs0gcoDVnPruAgABWgAFdmFsdWV4cAE=", subject.method2(null, 1, new byte[]{}, 1, -1));
    }

    @Test
    void method2Case04() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.NullPointerException.class, () -> subject.method2(null, 1, new byte[]{}, 1, 1));
    }

}
