package equivalent;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static equivalent.ClonePairGenericInvocationTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ClonePair10965DifferenceFindingTest {

    private final ClonePair10965 subject = new ClonePair10965();

    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: exception.
     * Difference manifestation: the methods differ in thrown exceptions or normal completion.
     */
    @Test
    @BehavioralDifference(DifferenceType.EXCEPTION)
    void methodsDisagreeOnGeneratedInput() {
        Object[] inputs = new Object[]{null, null};
        InvocationOutcome method1Outcome = capture(values -> subject.method1((Class) values[0], (Object) values[1]), inputs);
        InvocationOutcome method2Outcome = capture(values -> subject.method2((Class) values[0], (Object) values[1]), inputs);

        assertCoreOutcome(
            method1Outcome,
            "EX",
            null,
            "java.lang.NullPointerException",
            "java.lang.Object[][null,null]",
            "java.lang.Object[][null,null]"
        );
        assertCoreOutcome(
            method2Outcome,
            "OK",
            "Boolean(true)",
            null,
            "java.lang.Object[][null,null]",
            "java.lang.Object[][null,null]"
        );
        assertTextEquals("stdout", "", method1Outcome.stdout);
        assertTextEquals("stdout", "", method2Outcome.stdout);
        assertTextEquals("stderr", "", method1Outcome.stderr);
        assertTextEquals("stderr", "", method2Outcome.stderr);
    }
}
