package equivalent;

import org.junit.jupiter.api.Test;

import static equivalent.ClonePairGeneratedTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair13562Method2Test {

    private final ClonePair13562 subject = new ClonePair13562();

    @Test
    void method2Case01() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXA=", subject.method2(null));
    }

    @Test
    void method2Case02() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbQqzzF/gGCFTgAgAAeHAAAAAA", subject.method2("0"));
    }

    @Test
    void method2Case03() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbQqzzF/gGCFTgAgAAeHAAAAABAA==", subject.method2("00"));
    }

    @Test
    void method2Case04() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbQqzzF/gGCFTgAgAAeHAAAAABCg==", subject.method2("0A"));
    }

    @Test
    void method2Case05() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbQqzzF/gGCFTgAgAAeHAAAAABfw==", subject.method2("7F"));
    }

}
