package equivalent;

import org.junit.jupiter.api.Test;

import static equivalent.ClonePairGeneratedTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair9905Method1Test {

    private final ClonePair9905 subject = new ClonePair9905();

    @Test
    void method1Case01() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.NullPointerException.class, () -> subject.method1(null));
    }

    @Test
    void method1Case02() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAANbW0kX9+RPGY+JPAIAAHhwAAAABXVyAAJbSU26YCZ26rKlAgAAeHAAAAAFAAAAQQAAAEYAAABMAAAAUQAAAFZ1cQB+AAIAAAAFAAAAQgAAAEcAAABNAAAAUgAAAFd1cQB+AAIAAAAFAAAAQwAAAEgAAABOAAAAUwAAAFh1cQB+AAIAAAAFAAAARAAAAEkAAABPAAAAVAAAAFl1cQB+AAIAAAAFAAAARQAAAEsAAABQAAAAVQAAAFo=", subject.method1(""));
    }

    @Test
    void method1Case03() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAANbW0kX9+RPGY+JPAIAAHhwAAAABXVyAAJbSU26YCZ26rKlAgAAeHAAAAAFAAAAQgAAAEYAAABMAAAAUQAAAFZ1cQB+AAIAAAAFAAAAQQAAAEcAAABNAAAAUgAAAFd1cQB+AAIAAAAFAAAAQwAAAEgAAABOAAAAUwAAAFh1cQB+AAIAAAAFAAAARAAAAEkAAABPAAAAVAAAAFl1cQB+AAIAAAAFAAAARQAAAEsAAABQAAAAVQAAAFo=", subject.method1("a.b"));
    }

    @Test
    void method1Case04() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAANbW0kX9+RPGY+JPAIAAHhwAAAABXVyAAJbSU26YCZ26rKlAgAAeHAAAAAFAAAAQwAAAEYAAABMAAAAUQAAAFZ1cQB+AAIAAAAFAAAAQQAAAEcAAABNAAAAUgAAAFd1cQB+AAIAAAAFAAAAQgAAAEgAAABOAAAAUwAAAFh1cQB+AAIAAAAFAAAARAAAAEkAAABPAAAAVAAAAFl1cQB+AAIAAAAFAAAARQAAAEsAAABQAAAAVQAAAFo=", subject.method1("a.b.c"));
    }

}
