package equivalent;

import org.junit.jupiter.api.Test;

import static equivalent.ClonePairGeneratedTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair7504Method1Test {

    private final ClonePair7504 subject = new ClonePair7504();

    @Test
    void method1Case01() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.NullPointerException.class, () -> subject.method1(null));
    }

    @Test
    void method1Case02() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXNyABBqYXZhLmxhbmcuRG91YmxlgLPCSilr+wQCAAFEAAV2YWx1ZXhyABBqYXZhLmxhbmcuTnVtYmVyhqyVHQuU4IsCAAB4cAAAAAAAAAAA", subject.method1(list()));
    }

    @Test
    void method1Case03() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXNyABBqYXZhLmxhbmcuRG91YmxlgLPCSilr+wQCAAFEAAV2YWx1ZXhyABBqYXZhLmxhbmcuTnVtYmVyhqyVHQuU4IsCAAB4cD/wAAAAAAAA", subject.method1(list(Double.valueOf(1.0))));
    }

    @Test
    void method1Case04() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXNyABBqYXZhLmxhbmcuRG91YmxlgLPCSilr+wQCAAFEAAV2YWx1ZXhyABBqYXZhLmxhbmcuTnVtYmVyhqyVHQuU4IsCAAB4cD/4AAAAAAAA", subject.method1(list(Double.valueOf(1.0), Double.valueOf(2.0))));
    }

    @Test
    void method1Case05() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXNyABBqYXZhLmxhbmcuRG91YmxlgLPCSilr+wQCAAFEAAV2YWx1ZXhyABBqYXZhLmxhbmcuTnVtYmVyhqyVHQuU4IsCAAB4cAAAAAAAAAAA", subject.method1(list(Double.valueOf(-1.0), Double.valueOf(0.0), Double.valueOf(1.0))));
    }

}
