package equivalent;

import org.junit.jupiter.api.Test;

import static equivalent.ClonePairGeneratedTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair10966Method2Test {

    private final ClonePair10966 subject = new ClonePair10966();

    @Test
    void method2Case01() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.NullPointerException.class, () -> subject.method2(null, ""));
    }

    @Test
    void method2Case02() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXA=", subject.method2(String.class, null));
    }

    @Test
    void method2Case03() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAA==", subject.method2(String.class, ""));
    }

    @Test
    void method2Case04() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.NumberFormatException.class, () -> subject.method2(Integer.class, ""));
    }

    @Test
    void method2Case05() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAWE=", subject.method2(String.class, "a"));
    }

}
