package equivalent;

import org.junit.jupiter.api.Test;

import static equivalent.ClonePairGeneratedTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair7430Method1Test {

    private final ClonePair7430 subject = new ClonePair7430();

    @Test
    void method1Case01() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXNyABFqYXZhLmxhbmcuQm9vbGVhbs0gcoDVnPruAgABWgAFdmFsdWV4cAE=", subject.method1("a", "a"));
    }

    @Test
    void method1Case02() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXNyABFqYXZhLmxhbmcuQm9vbGVhbs0gcoDVnPruAgABWgAFdmFsdWV4cAA=", subject.method1(null, "a"));
    }

    @Test
    void method1Case03() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXNyABFqYXZhLmxhbmcuQm9vbGVhbs0gcoDVnPruAgABWgAFdmFsdWV4cAE=", subject.method1("A", "a"));
    }

    @Test
    void method1Case04() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXNyABFqYXZhLmxhbmcuQm9vbGVhbs0gcoDVnPruAgABWgAFdmFsdWV4cAA=", subject.method1(Integer.valueOf(1), "a"));
    }

}
