package equivalent;

import org.junit.jupiter.api.Test;

import static equivalent.ClonePairGeneratedTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair3913Method1Test {

    private final ClonePair3913 subject = new ClonePair3913();

    @Test
    void method1Case01() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.NullPointerException.class, () -> subject.method1(null, "", -1.0));
    }

    @Test
    void method1Case02() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXNyABBqYXZhLmxhbmcuRG91YmxlgLPCSilr+wQCAAFEAAV2YWx1ZXhyABBqYXZhLmxhbmcuTnVtYmVyhqyVHQuU4IsCAAB4cL/wAAAAAAAA", subject.method1(props(), "", -1.0));
    }

    @Test
    void method1Case03() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXNyABBqYXZhLmxhbmcuRG91YmxlgLPCSilr+wQCAAFEAAV2YWx1ZXhyABBqYXZhLmxhbmcuTnVtYmVyhqyVHQuU4IsCAAB4cAAAAAAAAAAA", subject.method1(props(), "", 0.0));
    }

    @Test
    void method1Case04() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXNyABBqYXZhLmxhbmcuRG91YmxlgLPCSilr+wQCAAFEAAV2YWx1ZXhyABBqYXZhLmxhbmcuTnVtYmVyhqyVHQuU4IsCAAB4cD/gAAAAAAAA", subject.method1(props(), "", 0.5));
    }

    @Test
    void method1Case05() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXNyABBqYXZhLmxhbmcuRG91YmxlgLPCSilr+wQCAAFEAAV2YWx1ZXhyABBqYXZhLmxhbmcuTnVtYmVyhqyVHQuU4IsCAAB4cL/wAAAAAAAA", subject.method1(props("a", "1"), "", -1.0));
    }

}
