package equivalent;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair8860DifferenceFindingTest {

    private final ClonePair8860 subject = new ClonePair8860();

    /**
     * Generated by Codex (GPT-5.5).
     */
    @Test
    void offsetAndLengthOverflowBypassesMethod1GuardButMethod2ReturnsNull() {
        byte[] input = {};
        int offset = Integer.MAX_VALUE;
        int length = 1;

        assertThrows(ArrayIndexOutOfBoundsException.class, () -> subject.method1(input, offset, length));
        assertNull(subject.method2(input, offset, length));
    }
}
