package equivalent;

import org.junit.jupiter.api.Test;

import static equivalent.ClonePairGeneratedTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair1830Method1Test {

    private final ClonePair1830 subject = new ClonePair1830();

    @Test
    void method1Case01() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.NullPointerException.class, () -> subject.method1(null));
    }

    @Test
    void method1Case02() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAA==", subject.method1(list()));
    }

    @Test
    void method1Case03() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQABmFscGhhCg==", subject.method1(list("alpha")));
    }

    @Test
    void method1Case04() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAC2FscGhhCmJldGEK", subject.method1(list("alpha", "beta")));
    }

    @Test
    void method1Case05() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAC2JldGEKZ2FtbWEK", subject.method1(list("beta", "gamma")));
    }

}
