package equivalent;

import org.junit.jupiter.api.Test;

import static equivalent.ClonePairGeneratedTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair3662Method2Test {

    private final ClonePair3662 subject = new ClonePair3662();

    @Test
    void method2Case01() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.NullPointerException.class, () -> subject.method2(null, 1, '\0', false));
    }

    @Test
    void method2Case02() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAsCA", subject.method2("", 1, '\0', false));
    }

    @Test
    void method2Case03() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAWE=", subject.method2("a", 1, '\0', false));
    }

    @Test
    void method2Case04() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAUE=", subject.method2("A", 1, '\0', false));
    }

    @Test
    void method2Case05() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAA==", subject.method2("", -1, '\0', false));
    }

}
