package equivalent;

import org.junit.jupiter.api.Test;

import static equivalent.ClonePairGeneratedTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair922Method2Test {

    private final ClonePair922 subject = new ClonePair922();

    @Test
    void method2Case01() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.NullPointerException.class, () -> subject.method2(null, 1));
    }

    @Test
    void method2Case02() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAA==", subject.method2(new byte[]{}, 1));
    }

    @Test
    void method2Case03() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQABTAxXzAy", subject.method2(new byte[]{0, 1, 2}, 1));
    }

    @Test
    void method2Case04() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQACDAyXzAzXzA0", subject.method2(new byte[]{1, 2, 3, 4}, 1));
    }

    @Test
    void method2Case05() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAFDAxXzAyXzAzXzA0XzA1XzA2XzA3", subject.method2(new byte[]{0, 1, 2, 3, 4, 5, 6, 7}, 1));
    }

}
