package equivalent;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ClonePair5151DifferenceFindingTest {

    private final ClonePair5151 subject = new ClonePair5151();

    /**
     * Generated by Codex (GPT-5.5).
     */
    @Test
    void methodsComparePositiveInfinityPairsDifferently() {
        double[] left = {Double.POSITIVE_INFINITY};
        double[] right = {Double.POSITIVE_INFINITY};

        assertTrue(subject.method1(left, right));
        assertFalse(subject.method2(left, right));
    }
}
