package equivalent;

import org.junit.jupiter.api.Test;

import static equivalent.ClonePairDifferenceTestSupport.*;

class ClonePair9489DifferenceTest {

    private final ClonePair9489 subject = new ClonePair9489();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertThrowsByName("java.lang.StringIndexOutOfBoundsException", () -> subject.method1("\t", 0));
        assertExpectedSerialized("rO0ABXNyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAAAB", subject.method2("\t", 0));
    }
}
