package equivalent;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair6251DifferenceFindingTest {

    private final ClonePair6251 subject = new ClonePair6251();

    /**
     * Generated by Codex (GPT-5.5).
     */
    @Test
    void offsetOverflowSkipsMethod2BigEndianLoopButMethod1ReadsArray() {
        byte[] input = {};
        int offset = Integer.MAX_VALUE;

        assertThrows(ArrayIndexOutOfBoundsException.class, () -> subject.method1(input, offset, false));
        assertEquals(0, subject.method2(input, offset, false));
    }
}
