package equivalent;

import org.junit.jupiter.api.Test;

import static equivalent.ClonePairGeneratedTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair8005Method1Test {

    private final ClonePair8005 subject = new ClonePair8005();

    @Test
    void method1Case01() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.NullPointerException.class, () -> subject.method1(null));
    }

    @Test
    void method1Case02() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbSU26YCZ26rKlAgAAeHAAAAAA", subject.method1(new byte[]{}));
    }

    @Test
    void method1Case03() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbSU26YCZ26rKlAgAAeHAAAAABAAAAAA==", subject.method1(new byte[]{0}));
    }

    @Test
    void method1Case04() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbSU26YCZ26rKlAgAAeHAAAAABAAECAA==", subject.method1(new byte[]{0, 1, 2}));
    }

    @Test
    void method1Case05() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbSU26YCZ26rKlAgAAeHAAAAABAQIDBA==", subject.method1(new byte[]{1, 2, 3, 4}));
    }

}
