package equivalent;

import org.junit.jupiter.api.Test;

import static equivalent.ClonePairGeneratedTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair12596Method2Test {

    private final ClonePair12596 subject = new ClonePair12596();

    @Test
    void method2Case01() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.ArrayIndexOutOfBoundsException.class, () -> subject.method2(d2(), 1));
    }

    @Test
    void method2Case02() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXA=", subject.method2(null, -1));
    }

    @Test
    void method2Case03() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAANbW0THrQv/ZGf/RQIAAHhwAAAAAXVyAAJbRD6mjBSrY1oeAgAAeHAAAAABAAAAAAAAAAA=", subject.method2(d2(new double[]{0.0}), 1));
    }

    @Test
    void method2Case04() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.NullPointerException.class, () -> subject.method2(null, 1));
    }

    @Test
    void method2Case05() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAANbW0THrQv/ZGf/RQIAAHhwAAAAAnVyAAJbRD6mjBSrY1oeAgAAeHAAAAACP/AAAAAAAABAAAAAAAAAAHVxAH4AAgAAAAJACAAAAAAAAEAQAAAAAAAA", subject.method2(d2(new double[]{1.0, 2.0}, new double[]{3.0, 4.0}), 1));
    }

}
