package equivalent;

import org.junit.jupiter.api.Test;

import static equivalent.ClonePairGeneratedTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair9468Method1Test {

    private final ClonePair9468 subject = new ClonePair9468();

    @Test
    void method1Case01() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.NullPointerException.class, () -> subject.method1(null));
    }

    @Test
    void method1Case02() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAjAx", subject.method1(calendar(0L)));
    }

    @Test
    void method1Case03() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAjAy", subject.method1(calendar(86_400_000L)));
    }

    @Test
    void method1Case04() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAjEy", subject.method1(calendar(1_000_000_000L)));
    }

}
