package equivalent;

import org.junit.jupiter.api.Test;

import static equivalent.ClonePairGeneratedTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair9905Method2Test {

    private final ClonePair9905 subject = new ClonePair9905();

    @Test
    void method2Case01() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.NullPointerException.class, () -> subject.method2(null));
    }

    @Test
    void method2Case02() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAANbW0kX9+RPGY+JPAIAAHhwAAAABXVyAAJbSU26YCZ26rKlAgAAeHAAAAAFAAAAQQAAAEYAAABMAAAAUQAAAFZ1cQB+AAIAAAAFAAAAQgAAAEcAAABNAAAAUgAAAFd1cQB+AAIAAAAFAAAAQwAAAEgAAABOAAAAUwAAAFh1cQB+AAIAAAAFAAAARAAAAEkAAABPAAAAVAAAAFl1cQB+AAIAAAAFAAAARQAAAEsAAABQAAAAVQAAAFo=", subject.method2(""));
    }

    @Test
    void method2Case03() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAANbW0kX9+RPGY+JPAIAAHhwAAAABXVyAAJbSU26YCZ26rKlAgAAeHAAAAAFAAAAQgAAAEYAAABMAAAAUQAAAFZ1cQB+AAIAAAAFAAAAQQAAAEcAAABNAAAAUgAAAFd1cQB+AAIAAAAFAAAAQwAAAEgAAABOAAAAUwAAAFh1cQB+AAIAAAAFAAAARAAAAEkAAABPAAAAVAAAAFl1cQB+AAIAAAAFAAAARQAAAEsAAABQAAAAVQAAAFo=", subject.method2("a.b"));
    }

    @Test
    void method2Case04() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAANbW0kX9+RPGY+JPAIAAHhwAAAABXVyAAJbSU26YCZ26rKlAgAAeHAAAAAFAAAAQwAAAEYAAABMAAAAUQAAAFZ1cQB+AAIAAAAFAAAAQQAAAEcAAABNAAAAUgAAAFd1cQB+AAIAAAAFAAAAQgAAAEgAAABOAAAAUwAAAFh1cQB+AAIAAAAFAAAARAAAAEkAAABPAAAAVAAAAFl1cQB+AAIAAAAFAAAARQAAAEsAAABQAAAAVQAAAFo=", subject.method2("a.b.c"));
    }

}
