package equivalent;

import org.junit.jupiter.api.Test;

import static equivalent.ClonePairGeneratedTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair13541Method1Test {

    private final ClonePair13541 subject = new ClonePair13541();

    @Test
    void method1Case01() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.StringIndexOutOfBoundsException.class, () -> subject.method1("0"));
    }

    @Test
    void method1Case02() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbQqzzF/gGCFTgAgAAeHAAAAABAA==", subject.method1("00"));
    }

    @Test
    void method1Case03() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbQqzzF/gGCFTgAgAAeHAAAAABCg==", subject.method1("0A"));
    }

    @Test
    void method1Case04() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.NullPointerException.class, () -> subject.method1(null));
    }

    @Test
    void method1Case05() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbQqzzF/gGCFTgAgAAeHAAAAABfw==", subject.method1("7F"));
    }

}
