package equivalent;

import org.junit.jupiter.api.Test;

import static equivalent.ClonePairGeneratedTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair7794Method2Test {

    private final ClonePair7794 subject = new ClonePair7794();

    @Test
    void method2Case01() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.NullPointerException.class, () -> subject.method2(null));
    }

    @Test
    void method2Case02() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbRgucgYki4AxCAgAAeHAAAAAA", subject.method2(new byte[]{}));
    }

    @Test
    void method2Case03() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbRgucgYki4AxCAgAAeHAAAAABAQIDBA==", subject.method2(new byte[]{1, 2, 3, 4}));
    }

    @Test
    void method2Case04() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbRgucgYki4AxCAgAAeHAAAAACAAECAwQFBgc=", subject.method2(new byte[]{0, 1, 2, 3, 4, 5, 6, 7}));
    }

}
