package equivalent;

import org.junit.jupiter.api.Test;

import static equivalent.ClonePairGeneratedTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair10314Method1Test {

    private final ClonePair10314 subject = new ClonePair10314();

    @Test
    void method1Case01() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.ArrayIndexOutOfBoundsException.class, () -> subject.method1(new byte[]{}, 1, 1));
    }

    @Test
    void method1Case02() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAjAx", subject.method1(new byte[]{0, 1, 2}, 1, 1));
    }

    @Test
    void method1Case03() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAA==", subject.method1(new byte[]{}, 1, -1));
    }

    @Test
    void method1Case04() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.NullPointerException.class, () -> subject.method1(null, 1, 1));
    }

    @Test
    void method1Case05() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAjAw", subject.method1(new byte[]{0}, 0, 1));
    }

}
