package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairDifferenceTestSupport.*;

class ClonePair12229DifferenceTest {

    private final ClonePair12229 subject = new ClonePair12229();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertThrowsByName("java.lang.NullPointerException", () -> subject.method1("010", "010", null));
        assertExpectedSerialized("rO0ABXQABG51bGw=", subject.method2("010", "010", null));
    }
}
