package unverified;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair13076DifferenceFindingTest {

    private final ClonePair13076 subject = new ClonePair13076();

    /**
     * Generated by Codex (GPT-5.5).
     * Difference type: exception.
     * Difference manifestation: the methods differ in thrown exceptions or normal completion.
     */
    @Test
    @BehavioralDifference(DifferenceType.EXCEPTION)
    void methodsHaveDifferentExceptionBehaviorForGeneratedInput() {
        Throwable method1Throwable = assertThrows(Throwable.class, () -> subject.method1("", null, null));
        assertDoesNotThrow(() -> { subject.method2("", null, null); });
    }
}
