package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairGenericInvocationTestSupport.*;

class ClonePair3962DifferenceFindingTest {

    private final ClonePair3962 subject = new ClonePair3962();

    /**
     * Generated by Codex (GPT-5.5).
     */
    @Test
    void methodsDisagreeOnSourceGuidedInput() {
        Object[] inputs = new Object[]{new byte[]{0}, new byte[]{-1}};
        InvocationOutcome method1Outcome = capture(values -> subject.method1((byte[]) values[0], (byte[]) values[1]), inputs);
        InvocationOutcome method2Outcome = capture(values -> subject.method2((byte[]) values[0], (byte[]) values[1]), inputs);

        assertCoreOutcome(
            method1Outcome,
            "OK",
            "Integer(1)",
            null,
            "java.lang.Object[][byte[][0],byte[][-1]]",
            "java.lang.Object[][byte[][0],byte[][-1]]"
        );
        assertTextEquals("stdout", "", method1Outcome.stdout);
        assertTextEquals("stderr", "", method1Outcome.stderr);
        assertCoreOutcome(
            method2Outcome,
            "OK",
            "Integer(-255)",
            null,
            "java.lang.Object[][byte[][0],byte[][-1]]",
            "java.lang.Object[][byte[][0],byte[][-1]]"
        );
        assertTextEquals("stdout", "", method2Outcome.stdout);
        assertTextEquals("stderr", "", method2Outcome.stderr);
    }
}
