package unverified;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairAliasAwareInvocationTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ClonePair12577DifferenceFindingTest {

    private final ClonePair12577 subject = new ClonePair12577();

    /**
     * Generated by Codex (GPT-5).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     * separating case: shared_0_2 ["sharedValue", "\"a\"", "sharedValue"]
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void methodsDisagreeOnGeneratedInput() {
        InvocationOutcome method1Outcome = captureWithTimeout(values -> subject.method1((String) values[0], (String) values[1], (String) values[2]), 1000L, buildMethod1Inputs());
        InvocationOutcome method2Outcome = captureWithTimeout(values -> subject.method2((String) values[0], (String) values[1], (String) values[2]), 1000L, buildMethod2Inputs());

        assertCoreOutcome(
            method1Outcome,
            "OK",
            "String(YWxpYWxpYXNz)",
            null,
            "java.lang.Object[][String(YWxpYXM=),String(YQ==),String(YWxpYXM=)]",
            "java.lang.Object[][String(YWxpYXM=),String(YQ==),String(YWxpYXM=)]"
        );
        assertCoreOutcome(
            method2Outcome,
            "OK",
            "String(YWxpYXNsaWFsaWFzcw==)",
            null,
            "java.lang.Object[][String(YWxpYXM=),String(YQ==),String(YWxpYXM=)]",
            "java.lang.Object[][String(YWxpYXM=),String(YQ==),String(YWxpYXM=)]"
        );
        assertTextEquals("stdout", "", method1Outcome.stdout);
        assertTextEquals("stdout", "", method2Outcome.stdout);
        assertTextEquals("stderr", "", method1Outcome.stderr);
        assertTextEquals("stderr", "", method2Outcome.stderr);
    }

    private Object[] buildMethod1Inputs() {
        String sharedValue = new String("alias");
        return new Object[]{sharedValue, "a", sharedValue};
    }

    private Object[] buildMethod2Inputs() {
        String sharedValue = new String("alias");
        return new Object[]{sharedValue, "a", sharedValue};
    }

}
