package unverified;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;
import static unverified.ClonePairDifferenceTestSupport.assertThrowsByName;

class ClonePair155DifferenceFindingTest {

    private final ClonePair155 subject = new ClonePair155();

    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: exception.
     * Difference manifestation: the methods differ in thrown exceptions or normal completion.
     */
    @Test
    @BehavioralDifference(DifferenceType.EXCEPTION)
    void methodsDisagreeOnNullArrayInputs() {
        assertThrowsByName("java.lang.NullPointerException", () -> subject.method1(null, null));
        assertTrue(subject.method2(null, null));
    }
}
