package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairDifferenceTestSupport.*;

class ClonePair13259DifferenceTest {

    private final ClonePair13259 subject = new ClonePair13259();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbQqzzF/gGCFTgAgAAeHAAAAAA", subject.method1("“ "));
        assertThrowsByName("java.lang.NumberFormatException", () -> subject.method2("“ "));
    }
}
