package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairAliasAwareInvocationTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ClonePair9990DifferenceFindingTest {

    private final ClonePair9990 subject = new ClonePair9990();

    /**
     * Generated by Codex (GPT-5).
     * separating case: novel_1_1 ["\"a\"", "new String(\"\")"]
     */
    @Test
    void methodsDisagreeOnGeneratedInput() {
        InvocationOutcome method1Outcome = captureWithTimeout(values -> subject.method1((String) values[0], (String) values[1]), 1000L, buildMethod1Inputs());
        InvocationOutcome method2Outcome = captureWithTimeout(values -> subject.method2((String) values[0], (String) values[1]), 1000L, buildMethod2Inputs());

        assertCoreOutcome(
            method1Outcome,
            "OK",
            "Integer(0)",
            null,
            "java.lang.Object[][String(YQ==),String()]",
            "java.lang.Object[][String(YQ==),String()]"
        );
        assertTextEquals("originalInputsSnapshot", "java.lang.Object[][String(YQ==),String()]", method2Outcome.originalInputsSnapshot);
        assertDifferent(method1Outcome, method2Outcome);
        assertTextEquals("stdout", "", method1Outcome.stdout);
        assertTextEquals("stdout", "", method2Outcome.stdout);
        assertTextEquals("stderr", "", method1Outcome.stderr);
        assertTextEquals("stderr", "", method2Outcome.stderr);
    }

    private Object[] buildMethod1Inputs() {
        return new Object[]{"a", new String("")};
    }

    private Object[] buildMethod2Inputs() {
        return new Object[]{"a", new String("")};
    }

}
