package unverified;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ClonePair114DifferenceFindingTest {

    private final ClonePair114 subject = new ClonePair114();

    /**
     * Generated by Codex (GPT-5.4).
     */
    @Test
    void methodsHandleNaNInputsDifferently() {
        assertEquals(1.0, subject.method1(Double.NaN, 1.0, 2.0), 0.0);
        assertTrue(Double.isNaN(subject.method2(Double.NaN, 1.0, 2.0)));
    }
}
