package unverified;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import static unverified.ClonePairGenericInvocationTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

@Tag("timeout")
class ClonePair13484DifferenceFindingTest {

    private final ClonePair13484 subject = new ClonePair13484();

    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: no_termination.
     * Difference manifestation: the methods differ in whether they terminate.
     */
    @Test
    @BehavioralDifference(DifferenceType.NO_TERMINATION)
    void methodsDisagreeOnGeneratedInput() {
        InvocationOutcome method1Outcome = captureWithTimeout(values -> subject.method1((String) values[0], (String) values[1], (String) values[2]), 200L, new Object[]{"", "", ""});
        InvocationOutcome method2Outcome = captureWithTimeout(values -> subject.method2((String) values[0], (String) values[1], (String) values[2]), 200L, new Object[]{"", "", ""});

        assertCoreOutcome(
            method1Outcome,
            "OK",
            "String()",
            null,
            "java.lang.Object[][String(),String(),String()]",
            "java.lang.Object[][String(),String(),String()]"
        );
        assertCoreOutcome(
            method2Outcome,
            "TIMEOUT",
            null,
            null,
            "java.lang.Object[][String(),String(),String()]",
            "java.lang.Object[][String(),String(),String()]"
        );
        assertTextEquals("stdout", "", method1Outcome.stdout);
        assertTextEquals("stdout", "", method2Outcome.stdout);
        assertTextEquals("stderr", "", method1Outcome.stderr);
        assertTextEquals("stderr", "", method2Outcome.stderr);
    }
}
