package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairDifferenceTestSupport.*;

class ClonePair11391DifferenceTest {

    private final ClonePair11391 subject = new ClonePair11391();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAzAxMA==", subject.method1("010", "010", "42.0", 0));
        assertExpectedSerialized("rO0ABXQABDQyLjA=", subject.method2("010", "010", "42.0", 0));
    }
}
