package unverified;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ClonePair983DifferenceFindingTest {

    private final ClonePair983 subject = new ClonePair983();

    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void methodsHandleInfiniteInputsDifferently() {
        assertFalse(subject.method1(Double.POSITIVE_INFINITY, Double.POSITIVE_INFINITY, 0.0));
        assertTrue(subject.method2(Double.POSITIVE_INFINITY, Double.POSITIVE_INFINITY, 0.0));
    }
}
