package unverified;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static unverified.ClonePairGenericInvocationTestSupport.*;

class ClonePair8195DifferenceFindingTest {

    private final ClonePair8195 subject = new ClonePair8195();

    /**
     * Generated by Codex (GPT-5.5).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void methodsReturnDifferentValuesForGeneratedInput() {
        InvocationOutcome method1Outcome = capture(values -> subject.method1((Object) values[0]), new Object[]{Double.valueOf(0.5)});
        InvocationOutcome method2Outcome = capture(values -> subject.method2((Object) values[0]), new Object[]{Double.valueOf(0.5)});

        assertEquals("OK", method1Outcome.status);
        assertNull(method1Outcome.exceptionClass);
        assertEquals("OK", method2Outcome.status);
        assertNull(method2Outcome.exceptionClass);
        assertNotEquals(method1Outcome.valueSnapshot, method2Outcome.valueSnapshot);
    }
}
