package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairDifferenceTestSupport.*;

class ClonePair10561DifferenceTest {

    private final ClonePair10561 subject = new ClonePair10561();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertThrowsByName("java.lang.NullPointerException", () -> subject.method1("", "", null));
        assertExpectedSerialized("rO0ABXQABG51bGw=", subject.method2("", "", null));
    }
}
