package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairGenericInvocationTestSupport.*;

class ClonePair9546DifferenceFindingTest {

    private final ClonePair9546 subject = new ClonePair9546();

    /**
     * Generated by Codex (GPT-5.5).
     */
    @Test
    void methodsDisagreeOnSourceGuidedInput() {
        Object[] inputs = new Object[]{new int[]{Integer.MAX_VALUE, Integer.MIN_VALUE}};
        InvocationOutcome method1Outcome = capture(values -> subject.method1((int[]) values[0]), inputs);
        InvocationOutcome method2Outcome = capture(values -> subject.method2((int[]) values[0]), inputs);

        assertCoreOutcome(
            method1Outcome,
            "OK",
            "Boolean(false)",
            null,
            "java.lang.Object[][int[][2147483647, -2147483648]]",
            "java.lang.Object[][int[][2147483647, -2147483648]]"
        );
        assertTextEquals("stdout", "", method1Outcome.stdout);
        assertTextEquals("stderr", "", method1Outcome.stderr);
        assertCoreOutcome(
            method2Outcome,
            "OK",
            "Boolean(true)",
            null,
            "java.lang.Object[][int[][2147483647, -2147483648]]",
            "java.lang.Object[][int[][2147483647, -2147483648]]"
        );
        assertTextEquals("stdout", "", method2Outcome.stdout);
        assertTextEquals("stderr", "", method2Outcome.stderr);
    }
}
