package unverified;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairGenericInvocationTestSupport.*;

class ClonePair11865DifferenceFindingTest {

    private final ClonePair11865 subject = new ClonePair11865();

    /**
     * Generated by Codex (GPT-5.5).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void methodsProduceDifferentObservableResultsForGeneratedInput() {
        Object[] inputs = new Object[] {"", Integer.MIN_VALUE};

        InvocationOutcome method1Outcome = capture(values -> subject.method1((String) values[0], ((Integer) values[1]).intValue()), inputs);
        InvocationOutcome method2Outcome = capture(values -> subject.method2((String) values[0], ((Integer) values[1]).intValue()), inputs);

        assertDifferent(method1Outcome, method2Outcome);
    }
}
