package unverified;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair11589DifferenceFindingTest {

    private final ClonePair11589 subject = new ClonePair11589();

    /**
     * Generated by Codex (GPT-5.5).
     */
    @Test
    void methodsHaveDifferentExceptionBehaviorForGeneratedInput() {
        assertDoesNotThrow(() -> { subject.method1("", null, null); });
        Throwable method2Throwable = assertThrows(Throwable.class, () -> subject.method2("", null, null));
    }
}
