package unverified;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static unverified.ClonePairGenericInvocationTestSupport.*;

class ClonePair9601DifferenceFindingTest {

    private final ClonePair9601 subject = new ClonePair9601();

    /**
     * Generated by Codex (GPT-5.5).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void methodsReturnDifferentValuesForGeneratedInput() {
        InvocationOutcome method1Outcome = capture(values -> subject.method1(((Character) values[0]).charValue()), new Object[]{'x'});
        InvocationOutcome method2Outcome = capture(values -> subject.method2(((Character) values[0]).charValue()), new Object[]{'x'});

        assertEquals("OK", method1Outcome.status);
        assertNull(method1Outcome.exceptionClass);
        assertEquals("OK", method2Outcome.status);
        assertNull(method2Outcome.exceptionClass);
        assertNotEquals(method1Outcome.valueSnapshot, method2Outcome.valueSnapshot);
    }
}
