package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairDifferenceTestSupport.*;

class ClonePair10953DifferenceTest {

    private final ClonePair10953 subject = new ClonePair10953();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAzAxMA==", subject.method1("010", 2, ""));
        assertExpectedSerialized("rO0ABXQAAjAx", subject.method2("010", 2, ""));
    }
}
