package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairGenericInvocationTestSupport.*;

class ClonePair3870DifferenceFindingTest {

    private final ClonePair3870 subject = new ClonePair3870();

    /**
     * Generated by Codex (GPT-5.5).
     */
    @Test
    void methodsDisagreeOnGeneratedInput() {
        Object[] inputs = new Object[]{-0.0, -0.0};
        InvocationOutcome method1Outcome = capture(values -> subject.method1(((Double) values[0]).doubleValue(), ((Double) values[1]).doubleValue()), inputs);
        InvocationOutcome method2Outcome = capture(values -> subject.method2(((Double) values[0]).doubleValue(), ((Double) values[1]).doubleValue()), inputs);

        assertCoreOutcome(
            method1Outcome,
            "OK",
            "Double(0.0)",
            null,
            "java.lang.Object[][Double(-0.0),Double(-0.0)]",
            "java.lang.Object[][Double(-0.0),Double(-0.0)]"
        );
        assertCoreOutcome(
            method2Outcome,
            "OK",
            "Double(-0.0)",
            null,
            "java.lang.Object[][Double(-0.0),Double(-0.0)]",
            "java.lang.Object[][Double(-0.0),Double(-0.0)]"
        );
        assertTextEquals("stdout", "", method1Outcome.stdout);
        assertTextEquals("stdout", "", method2Outcome.stdout);
        assertTextEquals("stderr", "", method1Outcome.stderr);
        assertTextEquals("stderr", "", method2Outcome.stderr);
        assertDifferent(method1Outcome, method2Outcome);
    }
}
