package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairGenericInvocationTestSupport.*;

class ClonePair136DifferenceFindingTest {

    private final ClonePair136 subject = new ClonePair136();

    /**
     * Generated by Codex (GPT-5.5).
     */
    @Test
    void methodsDisagreeOnGeneratedInput() {
        Object[] inputs = new Object[]{Double.NaN, Double.POSITIVE_INFINITY, Double.POSITIVE_INFINITY};
        InvocationOutcome method1Outcome = capture(values -> subject.method1(((Double) values[0]).doubleValue(), ((Double) values[1]).doubleValue(), ((Double) values[2]).doubleValue()), inputs);
        InvocationOutcome method2Outcome = capture(values -> subject.method2(((Double) values[0]).doubleValue(), ((Double) values[1]).doubleValue(), ((Double) values[2]).doubleValue()), inputs);

        assertCoreOutcome(
            method1Outcome,
            "OK",
            "Double(NaN)",
            null,
            "java.lang.Object[][Double(NaN),Double(Infinity),Double(Infinity)]",
            "java.lang.Object[][Double(NaN),Double(Infinity),Double(Infinity)]"
        );
        assertCoreOutcome(
            method2Outcome,
            "OK",
            "Double(Infinity)",
            null,
            "java.lang.Object[][Double(NaN),Double(Infinity),Double(Infinity)]",
            "java.lang.Object[][Double(NaN),Double(Infinity),Double(Infinity)]"
        );
        assertTextEquals("stdout", "", method1Outcome.stdout);
        assertTextEquals("stdout", "", method2Outcome.stdout);
        assertTextEquals("stderr", "", method1Outcome.stderr);
        assertTextEquals("stderr", "", method2Outcome.stderr);
        assertDifferent(method1Outcome, method2Outcome);
    }
}
