package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairDifferenceTestSupport.*;

class ClonePair10888DifferenceTest {

    private final ClonePair10888 subject = new ClonePair10888();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAzAxMA==", subject.method1("010", null, null));
        assertThrowsByName("java.lang.NullPointerException", () -> subject.method2("010", null, null));
    }
}
