package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairDifferenceTestSupport.*;

class ClonePair10772DifferenceTest {

    private final ClonePair10772 subject = new ClonePair10772();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQABG51bGw=", subject.method1("010", "010", null));
        assertExpectedSerialized("rO0ABXQAAA==", subject.method2("010", "010", null));
    }
}
