package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairDifferenceTestSupport.*;

class ClonePair12677DifferenceTest {

    private final ClonePair12677 subject = new ClonePair12677();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAjAx", subject.method1("010", '0'));
        assertExpectedSerialized("rO0ABXQAATE=", subject.method2("010", '0'));
    }
}
