package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairDifferenceTestSupport.*;

class ClonePair1919DifferenceTest {

    private final ClonePair1919 subject = new ClonePair1919();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXNyABFqYXZhLmxhbmcuQm9vbGVhbs0gcoDVnPruAgABWgAFdmFsdWV4cAA=", subject.method1(null, new byte[]{}));
        assertExpectedSerialized("rO0ABXNyABFqYXZhLmxhbmcuQm9vbGVhbs0gcoDVnPruAgABWgAFdmFsdWV4cAE=", subject.method2(null, new byte[]{}));
    }
}
