package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairDifferenceTestSupport.*;

class ClonePair10771DifferenceTest {

    private final ClonePair10771 subject = new ClonePair10771();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQABG51bGw=", subject.method1("010", "010", null));
        assertThrowsByName("java.lang.NullPointerException", () -> subject.method2("010", "010", null));
    }
}
