package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairGenericInvocationTestSupport.*;

class ClonePair6633DifferenceFindingTest {

    private final ClonePair6633 subject = new ClonePair6633();

    /**
     * Generated by Codex (GPT-5.5).
     */
    @Test
    void methodsProduceDifferentObservableResultsForGeneratedInput() {
        Object[] inputs = new Object[] {Integer.MIN_VALUE, 3};

        InvocationOutcome method1Outcome = capture(values -> subject.method1(((Integer) values[0]).intValue(), ((Integer) values[1]).intValue()), inputs);
        InvocationOutcome method2Outcome = capture(values -> subject.method2(((Integer) values[0]).intValue(), ((Integer) values[1]).intValue()), inputs);

        assertDifferent(method1Outcome, method2Outcome);
    }
}
