package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairDifferenceTestSupport.*;

class ClonePair10788DifferenceTest {

    private final ClonePair10788 subject = new ClonePair10788();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAmFh", subject.method1("aaa", "aa", "a"));
        assertExpectedSerialized("rO0ABXQAAWE=", subject.method2("aaa", "aa", "a"));
    }
}
