package unverified;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairGenericInvocationTestSupport.*;

class ClonePair4257DifferenceFindingTest {

    private final ClonePair4257 subject = new ClonePair4257();

    /**
     * Generated by Codex (GPT-5.5).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void methodsDisagreeOnGeneratedInput() {
        Object[] inputs = new Object[]{new float[]{Float.POSITIVE_INFINITY}, new float[]{Float.POSITIVE_INFINITY}};
        InvocationOutcome method1Outcome = capture(values -> subject.method1((float[]) values[0], (float[]) values[1]), inputs);
        InvocationOutcome method2Outcome = capture(values -> subject.method2((float[]) values[0], (float[]) values[1]), inputs);

        assertCoreOutcome(
            method1Outcome,
            "OK",
            "Boolean(true)",
            null,
            "java.lang.Object[][float[][Infinity],float[][Infinity]]",
            "java.lang.Object[][float[][Infinity],float[][Infinity]]"
        );
        assertCoreOutcome(
            method2Outcome,
            "OK",
            "Boolean(false)",
            null,
            "java.lang.Object[][float[][Infinity],float[][Infinity]]",
            "java.lang.Object[][float[][Infinity],float[][Infinity]]"
        );
        assertTextEquals("stdout", "", method1Outcome.stdout);
        assertTextEquals("stdout", "", method2Outcome.stdout);
        assertTextEquals("stderr", "", method1Outcome.stderr);
        assertTextEquals("stderr", "", method2Outcome.stderr);
        assertDifferent(method1Outcome, method2Outcome);
    }
}
