package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairDifferenceTestSupport.*;

class ClonePair11902DifferenceTest {

    private final ClonePair11902 subject = new ClonePair11902();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertThrowsByName("java.lang.NullPointerException", () -> subject.method1("010", null, null));
        assertExpectedSerialized("rO0ABXQAAzAxMA==", subject.method2("010", null, null));
    }
}
