package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairDifferenceTestSupport.*;

class ClonePair11577DifferenceTest {

    private final ClonePair11577 subject = new ClonePair11577();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXA=", subject.method1(null, null, null));
        assertThrowsByName("java.lang.NullPointerException", () -> subject.method2(null, null, null));
    }
}
