package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairGenericInvocationTestSupport.*;

class ClonePair4009DifferenceFindingTest {

    private final ClonePair4009 subject = new ClonePair4009();

    /**
     * Generated by Codex (GPT-5.5).
     */
    @Test
    void methodsDisagreeOnSourceGuidedInput() {
        Object[] inputs = new Object[]{null, "*"};
        InvocationOutcome method1Outcome = capture(values -> subject.method1((String) values[0], (String) values[1]), inputs);
        InvocationOutcome method2Outcome = capture(values -> subject.method2((String) values[0], (String) values[1]), inputs);

        assertCoreOutcome(
            method1Outcome,
            "OK",
            "Boolean(true)",
            null,
            "java.lang.Object[][null,String(Kg==)]",
            "java.lang.Object[][null,String(Kg==)]"
        );
        assertTextEquals("stdout", "", method1Outcome.stdout);
        assertTextEquals("stderr", "", method1Outcome.stderr);
        assertCoreOutcome(
            method2Outcome,
            "EX",
            null,
            "java.lang.NullPointerException",
            "java.lang.Object[][null,String(Kg==)]",
            "java.lang.Object[][null,String(Kg==)]"
        );
        assertTextEquals("stdout", "", method2Outcome.stdout);
        assertTextEquals("stderr", "", method2Outcome.stderr);
    }
}
