package unverified;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair12085DifferenceFindingTest {

    private final ClonePair12085 subject = new ClonePair12085();

    /**
     * Generated by Codex (GPT-5.5).
     */
    @Test
    void methodsHaveDifferentExceptionBehaviorForGeneratedInput() {
        Throwable method1Throwable = assertThrows(Throwable.class, () -> subject.method1("", null, null));
        assertDoesNotThrow(() -> { subject.method2("", null, null); });
    }
}
