package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairGenericInvocationTestSupport.*;

class ClonePair8921DifferenceFindingTest {

    private final ClonePair8921 subject = new ClonePair8921();

    /**
     * Generated by Codex (GPT-5.5).
     */
    @Test
    void methodsProduceDifferentObservableResultsForGeneratedInput() {
        Object[] inputs = new Object[] {null, 1, Integer.MAX_VALUE};

        InvocationOutcome method1Outcome = capture(values -> subject.method1((int[]) values[0], ((Integer) values[1]).intValue(), ((Integer) values[2]).intValue()), inputs);
        InvocationOutcome method2Outcome = capture(values -> subject.method2((int[]) values[0], ((Integer) values[1]).intValue(), ((Integer) values[2]).intValue()), inputs);

        assertDifferent(method1Outcome, method2Outcome);
    }
}
