package unverified;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairGenericInvocationTestSupport.*;

class ClonePair7209DifferenceFindingTest {

    private final ClonePair7209 subject = new ClonePair7209();

    /**
     * Generated by Codex (GPT-5.5).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void methodsProduceDifferentObservableResultsForGeneratedInput() {
        Object[] inputs = new Object[] {"a,b", "a,b"};

        InvocationOutcome method1Outcome = capture(values -> subject.method1((String) values[0], (String) values[1]), inputs);
        InvocationOutcome method2Outcome = capture(values -> subject.method2((String) values[0], (String) values[1]), inputs);

        assertDifferent(method1Outcome, method2Outcome);
    }
}
