package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairDifferenceTestSupport.*;

class ClonePair12875DifferenceTest {

    private final ClonePair12875 subject = new ClonePair12875();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAA==", subject.method1("010", "010", null));
        assertThrowsByName("java.lang.NullPointerException", () -> subject.method2("010", "010", null));
    }
}
