package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairDifferenceTestSupport.*;

class ClonePair2005DifferenceTest {

    private final ClonePair2005 subject = new ClonePair2005();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQABWFscGhh", subject.method1(list("alpha")));
        assertExpectedSerialized("rO0ABXQABmFscGhhIA==", subject.method2(list("alpha")));
    }
}
