package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairDifferenceTestSupport.*;

class ClonePair11665DifferenceTest {

    private final ClonePair11665 subject = new ClonePair11665();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQABG51bGw=", subject.method1("010", "010", null));
        assertThrowsByName("java.lang.NullPointerException", () -> subject.method2("010", "010", null));
    }
}
