package unverified;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairGenericInvocationTestSupport.*;

class ClonePair3188DifferenceFindingTest {

    private final ClonePair3188 subject = new ClonePair3188();

    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: exception.
     * Difference manifestation: the methods differ in thrown exceptions or normal completion.
     */
    @Test
    @BehavioralDifference(DifferenceType.EXCEPTION)
    void methodsDisagreeOnGeneratedInput() {
        InvocationOutcome method1Outcome = capture(values -> subject.method1((Object) values[0], (Object) values[1]), new Object[]{null, Integer.valueOf(7)});
        InvocationOutcome method2Outcome = capture(values -> subject.method2((Object) values[0], (Object) values[1]), new Object[]{null, Integer.valueOf(7)});

        assertOutcome(
            method1Outcome,
            "EX",
            null,
            "java.lang.NullPointerException",
            "",
            "",
            "java.lang.Object[][null,Integer(7)]",
            "java.lang.Object[][null,Integer(7)]"
        );
        assertOutcome(
            method2Outcome,
            "EX",
            null,
            "java.lang.ClassCastException",
            "",
            "",
            "java.lang.Object[][null,Integer(7)]",
            "java.lang.Object[][null,Integer(7)]"
        );
    }
}
