package unverified;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static unverified.ClonePairGenericInvocationTestSupport.*;

class ClonePair10007DifferenceFindingTest {

    private final ClonePair10007 subject = new ClonePair10007();

    /**
     * Generated by Codex (GPT-5.5).
     */
    @Test
    void methodsReturnDifferentValuesForGeneratedInput() {
        InvocationOutcome method1Outcome = capture(values -> subject.method1(((Double) values[0]).doubleValue()), new Object[]{-1.0e-11});
        InvocationOutcome method2Outcome = capture(values -> subject.method2(((Double) values[0]).doubleValue()), new Object[]{-1.0e-11});

        assertEquals("OK", method1Outcome.status);
        assertNull(method1Outcome.exceptionClass);
        assertEquals("OK", method2Outcome.status);
        assertNull(method2Outcome.exceptionClass);
        assertNotEquals(method1Outcome.valueSnapshot, method2Outcome.valueSnapshot);
    }
}
