package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairGenericInvocationTestSupport.*;

class ClonePair13311DifferenceFindingTest {

    private final ClonePair13311 subject = new ClonePair13311();

    /**
     * Generated by Codex (GPT-5.5).
     */
    @Test
    void methodsDisagreeOnSourceGuidedInput() {
        Object[] inputs = new Object[]{"-1"};
        InvocationOutcome method1Outcome = capture(values -> subject.method1((String) values[0]), inputs);
        InvocationOutcome method2Outcome = capture(values -> subject.method2((String) values[0]), inputs);

        assertCoreOutcome(
            method1Outcome,
            "OK",
            "byte[][-1]",
            null,
            "java.lang.Object[][String(LTE=)]",
            "java.lang.Object[][String(LTE=)]"
        );
        assertTextEquals("stdout", "", method1Outcome.stdout);
        assertTextEquals("stderr", "", method1Outcome.stderr);
        assertCoreOutcome(
            method2Outcome,
            "EX",
            null,
            "java.lang.NumberFormatException",
            "java.lang.Object[][String(LTE=)]",
            "java.lang.Object[][String(LTE=)]"
        );
        assertTextEquals("stdout", "", method2Outcome.stdout);
        assertTextEquals("stderr", "", method2Outcome.stderr);
    }
}
