package unverified;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair12938DifferenceFindingTest {

    private final ClonePair12938 subject = new ClonePair12938();

    /**
     * Generated by Codex (GPT-5.5).
     * Difference type: exception.
     * Difference manifestation: the methods differ in thrown exceptions or normal completion.
     */
    @Test
    @BehavioralDifference(DifferenceType.EXCEPTION)
    void methodsHaveDifferentExceptionBehaviorForGeneratedInput() {
        assertThrows(NullPointerException.class, () -> subject.method1("", null, null));
        assertEquals("", assertDoesNotThrow(() -> subject.method2("", null, null)));
    }
}
