package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairDifferenceTestSupport.*;

class ClonePair38348DifferenceTest {

    private final ClonePair38348 subject = new ClonePair38348();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQABCAwMTA=", subject.method1("010", 4));
        assertExpectedSerialized("rO0ABXQABDAwMTA=", subject.method2("010", 4));
    }
}
