package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairDifferenceTestSupport.*;

class ClonePair1680DifferenceTest {

    private final ClonePair1680 subject = new ClonePair1680();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQACmFscGhhCWJldGE=", subject.method1(list("alpha", "beta")));
        assertExpectedSerialized("rO0ABXQAC2FscGhhLCBiZXRh", subject.method2(list("alpha", "beta")));
    }
}
