package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairDifferenceTestSupport.*;

class ClonePair11308DifferenceTest {

    private final ClonePair11308 subject = new ClonePair11308();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQABCAwMTA=", subject.method1("010", 4));
        assertExpectedSerialized("rO0ABXQABDAwMTA=", subject.method2("010", 4));
    }
}
