package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairDifferenceTestSupport.*;

class ClonePair13465DifferenceTest {

    private final ClonePair13465 subject = new ClonePair13465();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertThrowsByName("java.lang.NullPointerException", () -> subject.method1("", null, null));
        assertExpectedSerialized("rO0ABXQAAA==", subject.method2("", null, null));
    }
}
