package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairDifferenceTestSupport.*;

class ClonePair10271DifferenceTest {

    private final ClonePair10271 subject = new ClonePair10271();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertThrowsByName("java.lang.NumberFormatException", () -> subject.method1("\t"));
        assertExpectedSerialized("rO0ABXA=", subject.method2("\t"));
    }
}
