package unverified;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairGenericInvocationTestSupport.*;

class ClonePair3788DifferenceFindingTest {

    private final ClonePair3788 subject = new ClonePair3788();

    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: side_effect.
     * Difference manifestation: the methods differ in observable side effects.
     */
    @Test
    @BehavioralDifference(DifferenceType.SIDE_EFFECT)
    void methodsDisagreeOnGeneratedInput() {
        InvocationOutcome method1Outcome = capture(values -> subject.method1((String) values[0], (String) values[1]), new Object[]{"a.b", "a"});
        InvocationOutcome method2Outcome = capture(values -> subject.method2((String) values[0], (String) values[1]), new Object[]{"a.b", "a"});
        String lineSeparator = System.lineSeparator();

        assertOutcome(
            method1Outcome,
            "OK",
            "Boolean(false)",
            null,
            "",
            "",
            "java.lang.Object[][String(YS5i),String(YQ==)]",
            "java.lang.Object[][String(YS5i),String(YQ==)]"
        );
        assertOutcome(
            method2Outcome,
            "OK",
            "Boolean(false)",
            null,
            "Compare failed: lengths differ" + lineSeparator,
            "",
            "java.lang.Object[][String(YS5i),String(YQ==)]",
            "java.lang.Object[][String(YS5i),String(YQ==)]"
        );
    }
}
