package unverified;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairGenericInvocationTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ClonePair10092DifferenceFindingTest {

    private final ClonePair10092 subject = new ClonePair10092();

    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void methodsDisagreeOnGeneratedInput() {
        InvocationOutcome method1Outcome = capture(values -> subject.method1((byte[]) values[0], ((Integer) values[1]).intValue(), ((Integer) values[2]).intValue()), new Object[]{new byte[]{0, 1, 2}, 1, 2});
        InvocationOutcome method2Outcome = capture(values -> subject.method2((byte[]) values[0], ((Integer) values[1]).intValue(), ((Integer) values[2]).intValue()), new Object[]{new byte[]{0, 1, 2}, 1, 2});

        assertCoreOutcome(
            method1Outcome,
            "OK",
            "Integer(258)",
            null,
            "java.lang.Object[][byte[][0, 1, 2],Integer(1),Integer(2)]",
            "java.lang.Object[][byte[][0, 1, 2],Integer(1),Integer(2)]"
        );
        assertCoreOutcome(
            method2Outcome,
            "OK",
            "Integer(3)",
            null,
            "java.lang.Object[][byte[][0, 1, 2],Integer(1),Integer(2)]",
            "java.lang.Object[][byte[][0, 1, 2],Integer(1),Integer(2)]"
        );
        assertTextEquals("stdout", "", method1Outcome.stdout);
        assertTextEquals("stdout", "", method2Outcome.stdout);
        assertTextEquals("stderr", "", method1Outcome.stderr);
        assertTextEquals("stderr", "", method2Outcome.stderr);
    }
}
