package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairGenericInvocationTestSupport.*;

class ClonePair4696DifferenceFindingTest {

    private final ClonePair4696 subject = new ClonePair4696();

    /**
     * Generated by Codex (GPT-5.5).
     */
    @Test
    void methodsDisagreeOnSourceGuidedInput() {
        Object[] inputs = new Object[]{1000};
        InvocationOutcome method1Outcome = capture(values -> subject.method1(((Integer) values[0]).intValue()), inputs);
        InvocationOutcome method2Outcome = capture(values -> subject.method2(((Integer) values[0]).intValue()), inputs);

        assertCoreOutcome(
            method1Outcome,
            "OK",
            "Boolean(false)",
            null,
            "java.lang.Object[][Integer(1000)]",
            "java.lang.Object[][Integer(1000)]"
        );
        assertTextEquals("stdout", "", method1Outcome.stdout);
        assertTextEquals("stderr", "", method1Outcome.stderr);
        assertCoreOutcome(
            method2Outcome,
            "OK",
            "Boolean(true)",
            null,
            "java.lang.Object[][Integer(1000)]",
            "java.lang.Object[][Integer(1000)]"
        );
        assertTextEquals("stdout", "", method2Outcome.stdout);
        assertTextEquals("stderr", "", method2Outcome.stderr);
    }
}
