package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairDifferenceTestSupport.*;

class ClonePair10421DifferenceTest {

    private final ClonePair10421 subject = new ClonePair10421();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertThrowsByName("java.lang.NullPointerException", () -> subject.method1(null, "010", null));
        assertExpectedSerialized("rO0ABXQAAA==", subject.method2(null, "010", null));
    }
}
