package unverified;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairGenericInvocationTestSupport.*;

class ClonePair10911DifferenceFindingTest {

    private final ClonePair10911 subject = new ClonePair10911();

    /**
     * Generated by Codex (GPT-5.5).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void methodsDisagreeOnGeneratedInput() {
        Object[] inputs = new Object[]{(char) 0x0800};
        InvocationOutcome method1Outcome = capture(values -> subject.method1(((Character) values[0]).charValue()), inputs);
        InvocationOutcome method2Outcome = capture(values -> subject.method2(((Character) values[0]).charValue()), inputs);

        assertCoreOutcome(
            method1Outcome,
            "OK",
            "Boolean(true)",
            null,
            "java.lang.Object[][Character(2048)]",
            "java.lang.Object[][Character(2048)]"
        );
        assertTextEquals("stdout", "", method1Outcome.stdout);
        assertTextEquals("stderr", "", method1Outcome.stderr);
        assertCoreOutcome(
            method2Outcome,
            "OK",
            "Boolean(false)",
            null,
            "java.lang.Object[][Character(2048)]",
            "java.lang.Object[][Character(2048)]"
        );
        assertTextEquals("stdout", "", method2Outcome.stdout);
        assertTextEquals("stderr", "", method2Outcome.stderr);
    }
}
