package unverified;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static unverified.ClonePairGenericInvocationTestSupport.*;

class ClonePair9891DifferenceFindingTest {

    private final ClonePair9891 subject = new ClonePair9891();

    /**
     * Generated by Codex (GPT-5.5).
     */
    @Test
    void methodsDisagreeOnRandomMetamorphicInput() {
        Object[] inputs = new Object[]{"\u0100", " "};
        InvocationOutcome method1Outcome = capture(values -> subject.method1((String) values[0], (String) values[1]), inputs);
        InvocationOutcome method2Outcome = capture(values -> subject.method2((String) values[0], (String) values[1]), inputs);

        assertEquals("OK", method1Outcome.status);
        assertEquals("Integer(224)", method1Outcome.valueSnapshot);
        assertEquals(null, method1Outcome.exceptionClass);
        assertEquals("OK", method2Outcome.status);
        assertEquals("Integer(225)", method2Outcome.valueSnapshot);
        assertEquals(null, method2Outcome.exceptionClass);
    }
}
