package unverified;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static unverified.ClonePairGenericInvocationTestSupport.*;

class ClonePair5289DifferenceFindingTest {

    private final ClonePair5289 subject = new ClonePair5289();

    /**
     * Generated by Codex (GPT-5.5).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void methodsReturnDifferentValuesForGeneratedInput() {
        InvocationOutcome method1Outcome = capture(values -> subject.method1((char[]) values[0], ((Integer) values[1]).intValue()), new Object[]{new char[]{'\f'}, 0});
        InvocationOutcome method2Outcome = capture(values -> subject.method2((char[]) values[0], ((Integer) values[1]).intValue()), new Object[]{new char[]{'\f'}, 0});

        assertEquals("OK", method1Outcome.status);
        assertNull(method1Outcome.exceptionClass);
        assertEquals("OK", method2Outcome.status);
        assertNull(method2Outcome.exceptionClass);
        assertNotEquals(method1Outcome.valueSnapshot, method2Outcome.valueSnapshot);
    }
}
