package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairAliasAwareInvocationTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ClonePair10634DifferenceFindingTest {

    private final ClonePair10634 subject = new ClonePair10634();

    /**
     * Generated by Codex (GPT-5).
     * separating case: novel_0_1 ["Double.POSITIVE_INFINITY"]
     */
    @Test
    void methodsDisagreeOnGeneratedInput() {
        InvocationOutcome method1Outcome = captureWithTimeout(values -> subject.method1(((Double) values[0]).doubleValue()), 1000L, buildMethod1Inputs());
        InvocationOutcome method2Outcome = captureWithTimeout(values -> subject.method2(((Double) values[0]).doubleValue()), 1000L, buildMethod2Inputs());

        assertCoreOutcome(
            method1Outcome,
            "OK",
            "Double(Infinity)",
            null,
            "java.lang.Object[][Double(Infinity)]",
            "java.lang.Object[][Double(Infinity)]"
        );
        assertTextEquals("originalInputsSnapshot", "java.lang.Object[][Double(Infinity)]", method2Outcome.originalInputsSnapshot);
        assertDifferent(method1Outcome, method2Outcome);
        assertTextEquals("stdout", "", method1Outcome.stdout);
        assertTextEquals("stdout", "", method2Outcome.stdout);
        assertTextEquals("stderr", "", method1Outcome.stderr);
        assertTextEquals("stderr", "", method2Outcome.stderr);
    }

    private Object[] buildMethod1Inputs() {
        return new Object[]{Double.POSITIVE_INFINITY};
    }

    private Object[] buildMethod2Inputs() {
        return new Object[]{Double.POSITIVE_INFINITY};
    }

}
