package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairDifferenceTestSupport.*;

class ClonePair7756DifferenceTest {

    private final ClonePair7756 subject = new ClonePair7756();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbRD6mjBSrY1oeAgAAeHAAAAAA", subject.method1(new byte[]{}));
        assertExpectedSerialized("rO0ABXVyAAJbSnggBLUSsXWTAgAAeHAAAAAA", subject.method2(new byte[]{}));
    }
}
