package unverified;

import org.junit.jupiter.api.Test;

import static unverified.ClonePairDifferenceTestSupport.*;

class ClonePair8949DifferenceTest {

    private final ClonePair8949 subject = new ClonePair8949();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAANbW0kX9+RPGY+JPAIAAHhwAAAAAXVyAAJbSU26YCZ26rKlAgAAeHAAAAABAAAAAA==", subject.method1(i2(new int[]{0}), i2(new int[]{0})));
        assertExpectedSerialized("rO0ABXVyAANbW0kX9+RPGY+JPAIAAHhwAAAAAXVyAAJbSU26YCZ26rKlAgAAeHAAAAABf////w==", subject.method2(i2(new int[]{0}), i2(new int[]{0})));
    }
}
