package unverified;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair10791DifferenceFindingTest {

    private final ClonePair10791 subject = new ClonePair10791();

    /**
     * Generated by Codex (GPT-5.5).
     * Difference type: exception.
     * Difference manifestation: the methods differ in thrown exceptions or normal completion.
     */
    @Test
    @BehavioralDifference(DifferenceType.EXCEPTION)
    void methodsHaveDifferentExceptionBehaviorForGeneratedInput() {
        assertDoesNotThrow(() -> { subject.method1("", null, null); });
        Throwable method2Throwable = assertThrows(Throwable.class, () -> subject.method2("", null, null));
    }
}
