package inequivalent;

import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.Collections;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

class ClonePair1907Method1Test {

    private final ClonePair1907 subject = new ClonePair1907();

    @Test
    void method1ReturnsNullForNullOrEmptyList() {
        // Generated by Codex (gpt-5.4).
        assertNull(subject.method1(null));
        assertNull(subject.method1(Collections.emptyList()));
    }

    @Test
    void method1ReturnsFirstFirefoxMatchIgnoringCase() {
        // Generated by Codex (gpt-5.4).
        assertEquals("firefox", subject.method1(Arrays.asList("Chrome", "firefox", "Firefox")));
    }

    @Test
    void method1ReturnsFirstBrowserWhenFirefoxIsAbsent() {
        // Generated by Codex (gpt-5.4).
        assertEquals("Chrome", subject.method1(Arrays.asList("Chrome", "Safari")));
    }
}
