package inequivalent;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair2975Method2Test {

    private static final double DELTA = 1.0e-9;

    private final ClonePair2975 subject = new ClonePair2975();

    @Test
    void method2ParsesNumberAfterRemovingCommas() {
        // Generated by Codex (gpt-5.4).
        assertEquals(1234.0, subject.method2("1,234"), DELTA);
    }

    @Test
    void method2AllowsNegativeNumbers() {
        // Generated by Codex (gpt-5.4).
        assertEquals(-12.0, subject.method2("-12"), DELTA);
    }

    @Test
    void method2ReturnsZeroForOnlyHyphenOrInvalidInput() {
        // Generated by Codex (gpt-5.4).
        assertEquals(0.0, subject.method2("-"), DELTA);
        assertEquals(0.0, subject.method2("abc"), DELTA);
    }

    @Test
    void method2ThrowsNullPointerExceptionForNullInput() {
        // Generated by Codex (gpt-5.4).
        assertThrows(NullPointerException.class, () -> subject.method2(null));
    }
}
