package inequivalent;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ClonePair5920DifferenceFindingTest {
    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void testDifference() {
        ClonePair5920 clonePair = new ClonePair5920();

        assertEquals(-1, clonePair.method1(-2, -3));
        assertEquals(-3, clonePair.method2(-2, -3));
    }
}
