package inequivalent;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ClonePair4228DifferenceFindingTest {
    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void testDifference() {
        ClonePair4228 clonePair = new ClonePair4228();

        assertEquals(0.0f, clonePair.method1(-1.0f, -1.0f, -1.0f));
        assertEquals(1.0f, clonePair.method2(-1.0f, -1.0f, -1.0f));
    }
}
