package inequivalent;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ClonePair10967DifferenceFindingTest {
    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void methodsTrimTruncatedTextDifferently() {
        ClonePair10967 clonePair = new ClonePair10967();

        assertEquals(" x", clonePair.method1(" a", 1, "x"));
        assertEquals("x", clonePair.method2(" a", 1, "x"));
    }
}
