package inequivalent;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair12313DifferenceFindingTest {
    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: exception.
     * Difference manifestation: the methods differ in thrown exceptions or normal completion.
     */
    @Test
    @BehavioralDifference(DifferenceType.EXCEPTION)
    void methodsHandleNullReplacementDifferently() {
        ClonePair12313 clonePair = new ClonePair12313();

        assertThrows(NullPointerException.class, () -> clonePair.method1("a", "a", null));
        assertEquals("null", clonePair.method2("a", "a", null));
    }
}
