package inequivalent;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static inequivalent.ClonePairDifferenceTestSupport.assertThrowsByName;
import static org.junit.jupiter.api.Assertions.assertEquals;

class ClonePair4DifferenceFindingTest {

    private final ClonePair4 subject = new ClonePair4();

    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: exception.
     * Difference manifestation: the methods differ in thrown exceptions or normal completion.
     */
    @Test
    @BehavioralDifference(DifferenceType.EXCEPTION)
    void methodsInterpretSecSuffixDifferently() {
        assertEquals(42L, subject.method1("42(sec)"));
        assertThrowsByName("java.lang.NumberFormatException", () -> subject.method2("42(sec)"));
    }
}
