package inequivalent;

import org.junit.jupiter.api.Test;

import static inequivalent.ClonePairGeneratedTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair10072Method1Test {

    private final ClonePair10072 subject = new ClonePair10072();

    @Test
    void method1Case01() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXA=", subject.method1(""));
    }

    @Test
    void method1Case02() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXA=", subject.method1(null));
    }

    @Test
    void method1Case03() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXA=", subject.method1("foo"));
    }

}
