package inequivalent;

import org.junit.jupiter.api.Test;

import static inequivalent.ClonePairDifferenceTestSupport.*;

class ClonePair8913DifferenceTest {

    private final ClonePair8913 subject = new ClonePair8913();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbQqzzF/gGCFTgAgAAeHAAAAABAg==", subject.method1(new byte[]{0, 1, 2}, 1));
        assertExpectedSerialized("rO0ABXVyAAJbQqzzF/gGCFTgAgAAeHAAAAABAA==", subject.method2(new byte[]{0, 1, 2}, 1));
    }
}
