package inequivalent;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ClonePair8046DifferenceFindingTest {
    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void methodsHandleCaseDifferently() {
        ClonePair8046 clonePair = new ClonePair8046();
        String[] supported = {"A"};

        assertEquals(0, clonePair.method1(supported, "a"));
        assertEquals(-1, clonePair.method2(supported, "a"));
    }
}
