package inequivalent;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair2Method2Test {

    private static final double DELTA = 1.0e-9;

    private final ClonePair2 subject = new ClonePair2();

    @Test
    void method2ReturnsZeroForIdenticalArrays() {
        // Generated by Codex (gpt-5.4).
        Integer[] curr = {1, 2, 3};
        Integer[] orig = {1, 2, 3};

        assertEquals(0.0, subject.method2(curr, orig, 2, 2), DELTA);
    }

    @Test
    void method2ReturnsNormalizedEuclideanDifference() {
        // Generated by Codex (gpt-5.4).
        Integer[] curr = {3, -1, 10};
        Integer[] orig = {1, 2, 4};

        assertEquals(1.75, subject.method2(curr, orig, 2, 2), DELTA);
    }

    @Test
    void method2ReturnsZeroForEmptyArrays() {
        // Generated by Codex (gpt-5.4).
        Integer[] curr = {};
        Integer[] orig = {};

        assertEquals(0.0, subject.method2(curr, orig, 3, 4), DELTA);
    }

    @Test
    void method2ReturnsInfinityWhenDivisorIsZeroAndDifferenceExists() {
        // Generated by Codex (gpt-5.4).
        Integer[] curr = {5};
        Integer[] orig = {1};

        assertEquals(Double.POSITIVE_INFINITY, subject.method2(curr, orig, 0, 3), DELTA);
    }

    @Test
    void method2ThrowsNullPointerExceptionWhenCurrentArrayIsNull() {
        // Generated by Codex (gpt-5.4).
        Integer[] orig = {1};

        assertThrows(NullPointerException.class, () -> subject.method2(null, orig, 1, 1));
    }
}
