package inequivalent;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ClonePair9164DifferenceFindingTest {
    /**
     * Generated by Codex (GPT-5.4).
     */
    @Test
    void methodsHandleCaseDifferently() {
        ClonePair9164 clonePair = new ClonePair9164();

        assertTrue(clonePair.method1("A", "a"));
        assertFalse(clonePair.method2("A", "a"));
    }
}
