package inequivalent;

import org.junit.jupiter.api.Test;

import static inequivalent.ClonePairGeneratedTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair13413Method1Test {

    private final ClonePair13413 subject = new ClonePair13413();

    @Test
    void method1Case01() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.StringIndexOutOfBoundsException.class, () -> subject.method1("a"));
    }

    @Test
    void method1Case02() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbQqzzF/gGCFTgAgAAeHAAAAAA", subject.method1(""));
    }

    @Test
    void method1Case03() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbQqzzF/gGCFTgAgAAeHAAAAABqw==", subject.method1("ab"));
    }

    @Test
    void method1Case04() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.NullPointerException.class, () -> subject.method1(null));
    }

    @Test
    void method1Case05() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.NumberFormatException.class, () -> subject.method1("a.b"));
    }

}
