package inequivalent;

import org.junit.jupiter.api.Test;

import static inequivalent.ClonePairGeneratedTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair3802Method1Test {

    private final ClonePair3802 subject = new ClonePair3802();

    @Test
    void method1Case01() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.NegativeArraySizeException.class, () -> subject.method1(i2(), -1));
    }

    @Test
    void method1Case02() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbWlePIDkUuF3iAgAAeHAAAAAA", subject.method1(i2(), 0));
    }

    @Test
    void method1Case03() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbWlePIDkUuF3iAgAAeHAAAAABAA==", subject.method1(i2(), 1));
    }

    @Test
    void method1Case04() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbWlePIDkUuF3iAgAAeHAAAAACAAA=", subject.method1(i2(), 2));
    }

    @Test
    void method1Case05() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbWlePIDkUuF3iAgAAeHAAAAADAAAA", subject.method1(i2(), 3));
    }

}
