package inequivalent;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Collections;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ClonePair7843DifferenceFindingTest {
    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void methodsRequireSameRuntimeClassDifferently() {
        ClonePair7843 clonePair = new ClonePair7843();

        assertFalse(clonePair.method1(Collections.singletonList("a"), new ArrayList<>(Collections.singletonList("a"))));
        assertTrue(clonePair.method2(Collections.singletonList("a"), new ArrayList<>(Collections.singletonList("a"))));
    }
}
