package inequivalent;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static inequivalent.ClonePairDifferenceTestSupport.assertThrowsByName;
import static org.junit.jupiter.api.Assertions.assertEquals;

class ClonePair3243DifferenceFindingTest {

    private final ClonePair3243 subject = new ClonePair3243();

    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: exception.
     * Difference manifestation: the methods differ in thrown exceptions or normal completion.
     */
    @Test
    @BehavioralDifference(DifferenceType.EXCEPTION)
    void methodsHandleLongArgumentsDifferently() {
        assertEquals(-1, subject.method1(1L, 2L));
        assertThrowsByName("java.lang.ClassCastException", () -> subject.method2(1L, 2L));
    }
}
