package inequivalent;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ClonePair4401DifferenceFindingTest {
    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void testDifference() {
        ClonePair4401 clonePair = new ClonePair4401();

        assertEquals(0.5 * Math.sin(0.5 * Math.PI * 0.5), clonePair.method1(0.5, 0.0));
        assertEquals(0.34375, clonePair.method2(0.5, 0.0));
    }
}
