package inequivalent;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ClonePair7436DifferenceFindingTest {
    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void methodsPadOppositeSides() {
        ClonePair7436 clonePair = new ClonePair7436();

        assertEquals("a__", clonePair.method1("a", 3, '_'));
        assertEquals("_a", clonePair.method2("a", 3, '_'));
    }
}
