package inequivalent;

import org.junit.jupiter.api.Test;

import static inequivalent.ClonePairDifferenceTestSupport.*;

class ClonePair8756DifferenceTest {

    private final ClonePair8756 subject = new ClonePair8756();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbRgucgYki4AxCAgAAeHAAAAABQAAAAA==", subject.method1(new float[]{1.0f, 2.0f}, 1));
        assertExpectedSerialized("rO0ABXVyAAJbRgucgYki4AxCAgAAeHAAAAABAAAAAA==", subject.method2(new float[]{1.0f, 2.0f}, 1));
    }
}
