package inequivalent;

import org.junit.jupiter.api.Test;

import static inequivalent.ClonePairGeneratedTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair12700Method1Test {

    private final ClonePair12700 subject = new ClonePair12700();

    @Test
    void method1Case01() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.NegativeArraySizeException.class, () -> subject.method1(-1, -1));
    }

    @Test
    void method1Case02() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbSU26YCZ26rKlAgAAeHAAAAAA", subject.method1(0, -1));
    }

    @Test
    void method1Case03() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbSU26YCZ26rKlAgAAeHAAAAACAAAAAAAAAAE=", subject.method1(1, -1));
    }

    @Test
    void method1Case04() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbSU26YCZ26rKlAgAAeHAAAAAE/////wAAAAAAAAABAAAAAA==", subject.method1(2, -1));
    }

    @Test
    void method1Case05() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbSU26YCZ26rKlAgAAeHAAAAAGAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAA", subject.method1(3, -1));
    }

}
