package inequivalent;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ClonePair53DifferenceFindingTest {

    private final ClonePair53 subject = new ClonePair53();

    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void methodsAggregateLongArgumentsDifferently() {
        assertEquals(7L, subject.method1(3L, 4L));
        assertEquals(4L, subject.method2(3L, 4L));
    }
}
