package inequivalent;

import org.junit.jupiter.api.Test;

import java.util.Vector;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair143Method1Test {

    private final ClonePair143 subject = new ClonePair143();

    @Test
    void method1ReturnsIndexOfExactMatch() {
        // Generated by Codex (gpt-5.4).
        Vector<String> genes = new Vector<>();
        genes.add("BRCA1");
        genes.add("TP53");

        assertEquals(1, subject.method1(genes, "TP53"));
    }

    @Test
    void method1IsCaseSensitive() {
        // Generated by Codex (gpt-5.4).
        Vector<String> genes = new Vector<>();
        genes.add("BRCA1");

        assertEquals(-1, subject.method1(genes, "brca1"));
    }

    @Test
    void method1ReturnsFirstIndexForDuplicateEqualValue() {
        // Generated by Codex (gpt-5.4).
        Vector<String> genes = new Vector<>();
        genes.add("TP53");
        genes.add("BRCA1");
        genes.add("TP53");

        assertEquals(0, subject.method1(genes, "TP53"));
    }

    @Test
    void method1ThrowsNullPointerExceptionForNullSearchString() {
        // Generated by Codex (gpt-5.4).
        Vector<String> genes = new Vector<>();
        genes.add("TP53");

        assertThrows(NullPointerException.class, () -> subject.method1(genes, null));
    }
}
