package inequivalent;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ClonePair10521DifferenceFindingTest {
    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void methodsComputeDifferentByteAggregates() {
        ClonePair10521 clonePair = new ClonePair10521();
        byte[] bytes = {1, 2};

        assertEquals(33, clonePair.method1(bytes, 0, 2));
        assertEquals(3, clonePair.method2(bytes, 0, 2));
    }
}
