package inequivalent;

import org.junit.jupiter.api.Test;

import static inequivalent.ClonePairGeneratedTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair11457Method1Test {

    private final ClonePair11457 subject = new ClonePair11457();

    @Test
    void method1Case01() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.NullPointerException.class, () -> subject.method1(null));
    }

    @Test
    void method1Case02() {
        // Generated by Codex (gpt-5.4).
        assertDateCloseToNow(subject.method1(""));
    }

    @Test
    void method1Case03() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.NumberFormatException.class, () -> subject.method1("Key:\"Value\";Other:Two"));
    }

}
