package inequivalent;

import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.Collections;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair2006Method2Test {

    private final ClonePair2006 subject = new ClonePair2006();

    @Test
    void method2ReturnsEmptyStringForEmptyList() {
        // Generated by Codex (gpt-5.4).
        assertEquals("", subject.method2(Collections.emptyList()));
    }

    @Test
    void method2FormatsElementsAsNumberedLines() {
        // Generated by Codex (gpt-5.4).
        assertEquals("1=a\n2=b\n", subject.method2(Arrays.asList("a", "b")));
    }

    @Test
    void method2ThrowsNullPointerExceptionForNullList() {
        // Generated by Codex (gpt-5.4).
        assertThrows(NullPointerException.class, () -> subject.method2(null));
    }
}
