package inequivalent;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ClonePair8279DifferenceFindingTest {
    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void methodsCompareCommaSeparatedSetsDifferently() {
        ClonePair8279 clonePair = new ClonePair8279();

        assertFalse(clonePair.method1("a,b", "b,a"));
        assertTrue(clonePair.method2("a,b", "b,a"));
    }
}
