package inequivalent;

import org.junit.jupiter.api.Test;

import static inequivalent.ClonePairGeneratedTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair3801Method2Test {

    private final ClonePair3801 subject = new ClonePair3801();

    @Test
    void method2Case01() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.ArrayIndexOutOfBoundsException.class, () -> subject.method2(-1, -1, 1, new double[]{}, new double[]{}));
    }

    @Test
    void method2Case02() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXA=", subject.method2(-1, -1, -1, null, new double[]{}));
    }

    @Test
    void method2Case03() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbRD6mjBSrY1oeAgAAeHAAAAAA", subject.method2(-1, -1, -1, new double[]{}, new double[]{}));
    }

    @Test
    void method2Case04() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbRD6mjBSrY1oeAgAAeHAAAAABAAAAAAAAAAA=", subject.method2(-1, -1, -1, new double[]{0.0}, new double[]{}));
    }

    @Test
    void method2Case05() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbRD6mjBSrY1oeAgAAeHAAAAABP/AAAAAAAAA=", subject.method2(-1, -1, -1, new double[]{1.0}, new double[]{}));
    }

}
