package inequivalent;

import org.junit.jupiter.api.Test;

import static inequivalent.ClonePairDifferenceTestSupport.*;

class ClonePair1928DifferenceTest {

    private final ClonePair1928 subject = new ClonePair1928();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQACWFscGhhYmV0YQ==", subject.method1(list("alpha", "beta")));
        assertExpectedSerialized("rO0ABXQAC2FscGhhLCBiZXRh", subject.method2(list("alpha", "beta")));
    }
}
