package inequivalent;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

class ClonePair2719Method1Test {

    private final ClonePair2719 subject = new ClonePair2719();

    @Test
    void method1ReturnsNullForNullOrEmptyInput() {
        // Generated by Codex (gpt-5.4).
        assertNull(subject.method1(null, ","));
        assertNull(subject.method1("", ","));
    }

    @Test
    void method1TokenizesWithoutTrimmingWholeInput() {
        // Generated by Codex (gpt-5.4).
        assertArrayEquals(new String[]{" a ", " b "}, subject.method1(" a , b ", ","));
    }

    @Test
    void method1ReturnsNullWhenNoTokensExist() {
        // Generated by Codex (gpt-5.4).
        assertNull(subject.method1(",,,", ","));
    }
}
