package inequivalent;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ClonePair12591DifferenceFindingTest {
    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void methodsHandleZeroIncrementAtEqualBoundsDifferently() {
        ClonePair12591 clonePair = new ClonePair12591();

        assertFalse(clonePair.method1(0, 0, 0));
        assertTrue(clonePair.method2(0, 0, 0));
    }
}
