package inequivalent;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair78Method2Test {

    private final ClonePair78 subject = new ClonePair78();

    @Test
    void method2FindsTargetIgnoringCase() {
        // Generated by Codex (gpt-5.4).
        char[] source = "abRaCadabra".toCharArray();
        char[] target = "cAD".toCharArray();

        assertEquals(4, subject.method2(source, 0, source.length, target, 0, target.length, 2));
    }

    @Test
    void method2NormalizesNegativeFromIndexToZero() {
        // Generated by Codex (gpt-5.4).
        char[] source = "Hello".toCharArray();
        char[] target = "he".toCharArray();

        assertEquals(0, subject.method2(source, 0, source.length, target, 0, target.length, -5));
    }

    @Test
    void method2ReturnsMinusOneWhenTargetIsNotPresent() {
        // Generated by Codex (gpt-5.4).
        char[] source = "hello".toCharArray();
        char[] target = "zz".toCharArray();

        assertEquals(-1, subject.method2(source, 0, source.length, target, 0, target.length, 0));
    }

    @Test
    void method2ReturnsSourceCountWhenFromIndexIsPastEndAndTargetIsEmpty() {
        // Generated by Codex (gpt-5.4).
        char[] source = "hello".toCharArray();
        char[] target = "x".toCharArray();

        assertEquals(source.length, subject.method2(source, 0, source.length, target, 0, 0, source.length));
    }

    @Test
    void method2ReturnsFromIndexWhenTargetIsEmpty() {
        // Generated by Codex (gpt-5.4).
        char[] source = "hello".toCharArray();
        char[] target = "x".toCharArray();

        assertEquals(2, subject.method2(source, 0, source.length, target, 0, 0, 2));
    }

    @Test
    void method2ReturnsMinusOneWhenNullSourceIsShortCircuitedByBoundsCheck() {
        // Generated by Codex (gpt-5.4).
        char[] target = "he".toCharArray();

        assertEquals(-1, subject.method2(null, 0, 0, target, 0, target.length, 0));
    }

    @Test
    void method2ThrowsNullPointerExceptionWhenSourceIsNullAndSearchMustProceed() {
        // Generated by Codex (gpt-5.4).
        char[] target = "he".toCharArray();

        assertThrows(NullPointerException.class, () -> subject.method2(null, 0, 3, target, 0, target.length, 0));
    }
}
