package inequivalent;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;

class ClonePair8913DifferenceFindingTest {
    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void methodsTakeTailAndHeadDifferently() {
        ClonePair8913 clonePair = new ClonePair8913();
        byte[] input = {1, 2};

        assertArrayEquals(new byte[]{2}, clonePair.method1(input, 1));
        assertArrayEquals(new byte[]{1}, clonePair.method2(input, 1));
    }
}
