package inequivalent;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair140Method1Test {

    private final ClonePair140 subject = new ClonePair140();

    @Test
    void method1ProducesGrayWhenSaturationIsZero() {
        // Generated by Codex (gpt-5.4).
        assertEquals(0x7F7F7F, subject.method1(0.25f, 0.0f, 0.5f));
    }

    @Test
    void method1WrapsHueOfOneBackToRed() {
        // Generated by Codex (gpt-5.4).
        assertEquals(0xFF0000, subject.method1(1.0f, 1.0f, 1.0f));
    }

    @Test
    void method1ClampsSaturationAndValueBelowZeroToBlack() {
        // Generated by Codex (gpt-5.4).
        assertEquals(0x000000, subject.method1(0.2f, -1.0f, -1.0f));
    }

    @Test
    void method1ThrowsArrayIndexOutOfBoundsExceptionWhenTooFewComponentsAreProvided() {
        // Generated by Codex (gpt-5.4).
        assertThrows(ArrayIndexOutOfBoundsException.class, () -> subject.method1(0.1f, 0.2f));
    }
}
