package inequivalent;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ClonePair3199DifferenceFindingTest {

    private final ClonePair3199 subject = new ClonePair3199();

    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void methodsCompareLengthAndContentInDifferentOrder() {
        assertEquals(-1, subject.method1(new char[]{'A', 'B', 'C'}, new char[]{'a', 'b'}));
        assertEquals(1, subject.method2(new char[]{'A', 'B', 'C'}, new char[]{'a', 'b'}));
    }
}
