package inequivalent;

import org.junit.jupiter.api.Test;

import static inequivalent.ClonePairDifferenceTestSupport.*;

class ClonePair12152DifferenceTest {

    private final ClonePair12152 subject = new ClonePair12152();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQABHvvvJE=", subject.method1("{１}", 3));
        assertExpectedSerialized("rO0ABXQABXvvvJF9", subject.method2("{１}", 3));
    }
}
