package inequivalent;

import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.Collections;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair1724Method1Test {

    private final ClonePair1724 subject = new ClonePair1724();

    @Test
    void method1ReturnsEmptyStringForEmptyList() {
        // Generated by Codex (gpt-5.4).
        assertEquals("", subject.method1(Collections.emptyList()));
    }

    @Test
    void method1JoinsElementsWithCommaWithoutSpace() {
        // Generated by Codex (gpt-5.4).
        assertEquals("GET,POST,PUT", subject.method1(Arrays.asList("GET", "POST", "PUT")));
    }

    @Test
    void method1AppendsNullElementsAsNullString() {
        // Generated by Codex (gpt-5.4).
        assertEquals("GET,null", subject.method1(Arrays.asList("GET", null)));
    }

    @Test
    void method1ThrowsNullPointerExceptionForNullList() {
        // Generated by Codex (gpt-5.4).
        assertThrows(NullPointerException.class, () -> subject.method1(null));
    }
}
