package inequivalent;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ClonePair7860DifferenceFindingTest {
    /**
     * Generated by Codex (GPT-5.4).
     */
    @Test
    void methodsTreatPrefixAsMatchDifferently() {
        ClonePair7860 clonePair = new ClonePair7860();

        assertFalse(clonePair.method1("abc", "a"));
        assertTrue(clonePair.method2("abc", "a"));
    }
}
