package inequivalent;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ClonePair4818DifferenceFindingTest {
    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void testDifference() {
        ClonePair4818 clonePair = new ClonePair4818();

        assertFalse(clonePair.method1("xABC", "abc"));
        assertTrue(clonePair.method2("xABC", "abc"));
    }
}
