package inequivalent;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair74Method1Test {

    private final ClonePair74 subject = new ClonePair74();

    @Test
    void method1SplitsPlainWordsOnSpaces() {
        // Generated by Codex (gpt-5.4).
        assertEquals(List.of("alpha", "beta"), subject.method1("alpha beta"));
    }

    @Test
    void method1KeepsSpacesInsideQuotedToken() {
        // Generated by Codex (gpt-5.4).
        assertEquals(List.of("alpha beta", "gamma"), subject.method1("\"alpha beta\" gamma"));
    }

    @Test
    void method1IgnoresRepeatedSpacesBetweenTokens() {
        // Generated by Codex (gpt-5.4).
        assertEquals(List.of("alpha", "beta"), subject.method1("alpha  beta"));
    }

    @Test
    void method1CollectsRemainingCharactersForUnclosedQuote() {
        // Generated by Codex (gpt-5.4).
        assertEquals(List.of("alpha beta"), subject.method1("\"alpha beta"));
    }

    @Test
    void method1ThrowsNullPointerExceptionForNullInput() {
        // Generated by Codex (gpt-5.4).
        assertThrows(NullPointerException.class, () -> subject.method1(null));
    }
}
