package inequivalent;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ClonePair8346DifferenceFindingTest {
    /**
     * Generated by Codex (GPT-5.4).
     */
    @Test
    void methodsReturnMaximumAndMinimumDifferently() {
        ClonePair8346 clonePair = new ClonePair8346();
        double[] input = {1.0, 2.0};

        assertEquals(2.0, clonePair.method1(input, 2));
        assertEquals(1.0, clonePair.method2(input, 2));
    }
}
