package inequivalent;

import org.junit.jupiter.api.Test;

import static inequivalent.ClonePairGeneratedTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair6673Method2Test {

    private final ClonePair6673 subject = new ClonePair6673();

    @Test
    void method2Case01() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.ArrayIndexOutOfBoundsException.class, () -> subject.method2(f2(), f2()));
    }

    @Test
    void method2Case02() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXA=", subject.method2(f2(new float[]{0.0f}), f2(new float[]{1.0f, 2.0f}, new float[]{3.0f})));
    }

    @Test
    void method2Case03() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAANbW0Z3qo0Waf4ZdgIAAHhwAAAAAXVyAAJbRgucgYki4AxCAgAAeHAAAAABAAAAAA==", subject.method2(f2(new float[]{0.0f}), f2(new float[]{0.0f})));
    }

    @Test
    void method2Case04() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.NullPointerException.class, () -> subject.method2(null, f2()));
    }

    @Test
    void method2Case05() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXA=", subject.method2(f2(new float[]{1.0f, 2.0f}, new float[]{3.0f}), f2(new float[]{0.0f})));
    }

}
