package inequivalent;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ClonePair844Method2Test {

    private final ClonePair844 subject = new ClonePair844();

    @Test
    void method2ClearsLiteralCharactersFromDefaultAllowedSet() {
        // Generated by Codex (gpt-5.4).
        boolean[] table = subject.method2("[^ab]", "");

        assertFalse(table['a']);
        assertFalse(table['b']);
        assertTrue(table['c']);
    }

    @Test
    void method2SupportsHexAndDigitEscapes() {
        // Generated by Codex (gpt-5.4).
        boolean[] table = subject.method2("[^\\x41\\d]", "");

        assertFalse(table['A']);
        assertFalse(table['0']);
        assertFalse(table['9']);
        assertTrue(table['B']);
    }

    @Test
    void method2ExpandsCaseInsensitiveRangesWithZEscape() {
        // Generated by Codex (gpt-5.4).
        boolean[] table = subject.method2("[^\\z4143]", "i");

        assertFalse(table['A']);
        assertFalse(table['B']);
        assertFalse(table['C']);
        assertFalse(table['a']);
        assertFalse(table['b']);
        assertFalse(table['c']);
        assertTrue(table['D']);
    }
}
