package inequivalent;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ClonePair11860DifferenceFindingTest {
    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void methodsReplaceLastAndAllOccurrencesDifferently() {
        ClonePair11860 clonePair = new ClonePair11860();

        assertEquals("ax", clonePair.method1("aa", "a", "x"));
        assertEquals("xx", clonePair.method2("aa", "a", "x"));
    }
}
