package inequivalent;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ClonePair8908DifferenceFindingTest {
    /**
     * Generated by Codex (GPT-5.4).
     */
    @Test
    void methodsHandleNonIntegerNumbersDifferently() {
        ClonePair8908 clonePair = new ClonePair8908();

        assertFalse(clonePair.method1(1.5, false));
        assertTrue(clonePair.method2(1.5, false));
    }
}
