package inequivalent;

import org.junit.jupiter.api.Test;

import static inequivalent.ClonePairGeneratedTestSupport.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ClonePair3730Method2Test {

    private final ClonePair3730 subject = new ClonePair3730();

    @Test
    void method2Case01() {
        // Generated by Codex (gpt-5.4).
        assertThrows(java.lang.NegativeArraySizeException.class, () -> subject.method2(Long.valueOf(-1L), -1));
    }

    @Test
    void method2Case02() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXNyABBqYXZhLnV0aWwuQml0U2V0bv2Ifjk0qyEDAAFbAARiaXRzdAACW0p4cHVyAAJbSnggBLUSsXWTAgAAeHAAAAAAeA==", subject.method2(Long.valueOf(-1L), 0));
    }

    @Test
    void method2Case03() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXNyABBqYXZhLnV0aWwuQml0U2V0bv2Ifjk0qyEDAAFbAARiaXRzdAACW0p4cHVyAAJbSnggBLUSsXWTAgAAeHAAAAABAAAAAAAAAAF4", subject.method2(Long.valueOf(-1L), 1));
    }

    @Test
    void method2Case04() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXNyABBqYXZhLnV0aWwuQml0U2V0bv2Ifjk0qyEDAAFbAARiaXRzdAACW0p4cHVyAAJbSnggBLUSsXWTAgAAeHAAAAABAAAAAAAAAAN4", subject.method2(Long.valueOf(-1L), 2));
    }

    @Test
    void method2Case05() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXNyABBqYXZhLnV0aWwuQml0U2V0bv2Ifjk0qyEDAAFbAARiaXRzdAACW0p4cHVyAAJbSnggBLUSsXWTAgAAeHAAAAABAAAAAAAAAAd4", subject.method2(Long.valueOf(-1L), 3));
    }

}
