package inequivalent;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ClonePair1579Method1Test {

    private final ClonePair1579 subject = new ClonePair1579();

    @Test
    void method1ReturnsTrueForSameReference() {
        // Generated by Codex (gpt-5.4).
        byte[] data = {1, 2};

        assertTrue(subject.method1(data, data));
    }

    @Test
    void method1ReturnsFalseForDifferentLengths() {
        // Generated by Codex (gpt-5.4).
        assertFalse(subject.method1(new byte[]{1}, new byte[]{1, 2}));
    }

    @Test
    void method1ReturnsFalseForDifferentContent() {
        // Generated by Codex (gpt-5.4).
        assertFalse(subject.method1(new byte[]{1, 2}, new byte[]{1, 3}));
    }

    @Test
    void method1ReturnsTrueForEqualContent() {
        // Generated by Codex (gpt-5.4).
        assertTrue(subject.method1(new byte[]{1, 2}, new byte[]{1, 2}));
    }

    @Test
    void method1ThrowsNullPointerExceptionForNullArray() {
        // Generated by Codex (gpt-5.4).
        assertThrows(NullPointerException.class, () -> subject.method1(null, new byte[]{1}));
    }
}
