package inequivalent;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ClonePair10950DifferenceFindingTest {
    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void methodsPadOppositeSides() {
        ClonePair10950 clonePair = new ClonePair10950();

        assertEquals("ax", clonePair.method1("a", 2, "x"));
        assertEquals("xa", clonePair.method2("a", 2, "x"));
    }
}
