package inequivalent;

import org.junit.jupiter.api.Test;

import static inequivalent.ClonePairDifferenceTestSupport.*;

class ClonePair8408DifferenceTest {

    private final ClonePair8408 subject = new ClonePair8408();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbSU26YCZ26rKlAgAAeHAAAAABAAAAAA==", subject.method1(new int[]{1}, -1, -1, 1));
        assertExpectedSerialized("rO0ABXVyAAJbSU26YCZ26rKlAgAAeHAAAAABAAAAAQ==", subject.method2(new int[]{1}, -1, -1, 1));
    }
}
