package inequivalent;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import java.util.Calendar;
import java.util.Date;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ClonePair4333DifferenceFindingTest {
    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void testDifference() {
        ClonePair4333 clonePair = new ClonePair4333();

        Date first = date(2020, Calendar.JANUARY, 1, 1);
        Date second = date(2020, Calendar.JANUARY, 1, 2);

        assertFalse(clonePair.method1(first, second));
        assertTrue(clonePair.method2(first, second));
    }

    private static Date date(int year, int month, int day, int hour) {
        Calendar calendar = Calendar.getInstance();
        calendar.clear();
        calendar.set(year, month, day, hour, 0, 0);
        return calendar.getTime();
    }
}
