package inequivalent;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import java.util.Vector;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ClonePair9303DifferenceFindingTest {
    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void methodsQuoteCommandsWithSpacesDifferently() {
        ClonePair9303 clonePair = new ClonePair9303();
        Vector<String> commands = new Vector<>();
        commands.add("a b");

        assertEquals("a b", clonePair.method1(commands, 0, 1));
        assertEquals("\"a b\"", clonePair.method2(commands, 0, 1));
    }
}
