package inequivalent;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ClonePair844Method1Test {

    private final ClonePair844 subject = new ClonePair844();

    @Test
    void method1MarksLiteralCharactersAsAllowed() {
        // Generated by Codex (gpt-5.4).
        boolean[] table = subject.method1("[ab]", "");

        assertTrue(table['a']);
        assertTrue(table['b']);
        assertFalse(table['c']);
    }

    @Test
    void method1SupportsHexAndDigitEscapes() {
        // Generated by Codex (gpt-5.4).
        boolean[] table = subject.method1("[\\x41\\d]", "");

        assertTrue(table['A']);
        assertTrue(table['0']);
        assertTrue(table['9']);
        assertFalse(table['B']);
    }

    @Test
    void method1ExpandsCaseInsensitiveRangesWithZEscape() {
        // Generated by Codex (gpt-5.4).
        boolean[] table = subject.method1("[\\z4143]", "i");

        assertTrue(table['A']);
        assertTrue(table['B']);
        assertTrue(table['C']);
        assertTrue(table['a']);
        assertTrue(table['b']);
        assertTrue(table['c']);
        assertFalse(table['D']);
    }
}
