package inequivalent;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ClonePair6262Method2Test {

    private final ClonePair6262 subject = new ClonePair6262();

    @Test
    void method2ReturnsEmptyStringWhenNoCharactersAreRequested() {
        // Generated by Codex (gpt-5.4).
        assertEquals("", subject.method2(0, 0, 0));
    }

    @Test
    void method2GeneratesOnlyDigitsWhenOnlyDigitsAreRequested() {
        // Generated by Codex (gpt-5.4).
        String result = subject.method2(0, 3, 0);

        assertEquals(3, result.length());
        assertEquals(3, result.chars().filter(Character::isDigit).count());
        assertTrue(result.chars().allMatch(ch -> ch >= 33 && !Character.isWhitespace(ch)));
    }

    @Test
    void method2GeneratesRequestedMixOfLettersDigitsAndSpecialCharacters() {
        // Generated by Codex (gpt-5.4).
        String result = subject.method2(2, 1, 3);

        assertEquals(6, result.length());
        assertTrue(result.chars().filter(Character::isLetter).count() >= 2);
        assertTrue(result.chars().filter(Character::isDigit).count() >= 1);
        assertTrue(result.chars().allMatch(ch -> ch >= 33 && !Character.isWhitespace(ch)));
    }

}
