package inequivalent;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;

class ClonePair13393DifferenceFindingTest {

    private final ClonePair13393 subject = new ClonePair13393();

    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void methodsTreatTabOnlyInputDifferently() {
        assertArrayEquals(new String[]{""}, subject.method1("\t"));
        assertArrayEquals(new String[]{"\t"}, subject.method2("\t"));
    }
}
