package inequivalent;

import metadata.BehavioralDifference;
import metadata.DifferenceType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

class ClonePair9954DifferenceFindingTest {
    /**
     * Generated by Codex (GPT-5.4).
     * Difference type: return_value.
     * Difference manifestation: the methods return different values.
     */
    @Test
    @BehavioralDifference(DifferenceType.RETURN_VALUE)
    void methodsSkipStringValuesDifferently() {
        ClonePair9954 clonePair = new ClonePair9954();
        Object[] objects = {"x"};

        assertEquals("x", clonePair.method1(objects));
        assertNull(clonePair.method2(objects));
    }
}
