package inequivalent;

import org.junit.jupiter.api.Test;

import static inequivalent.ClonePairDifferenceTestSupport.*;

class ClonePair3669DifferenceTest {

    private final ClonePair3669 subject = new ClonePair3669();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertThrowsByName("java.lang.StringIndexOutOfBoundsException", () -> subject.method1("010", 1, '\0', true));
        assertExpectedSerialized("rO0ABXQAATA=", subject.method2("010", 1, '\0', true));
    }
}
