package inequivalent;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ClonePair948Method2Test {

    private final ClonePair948 subject = new ClonePair948();

    @Test
    void method2ReturnsTrueWhenFirstSixBytesMatch() {
        // Generated by Codex (gpt-5.4).
        assertTrue(subject.method2(new byte[]{1, 2, 3, 4, 5, 6}, new byte[]{1, 2, 3, 4, 5, 6}));
    }

    @Test
    void method2ReturnsFalseWhenAnyOfFirstSixBytesDiffers() {
        // Generated by Codex (gpt-5.4).
        assertFalse(subject.method2(new byte[]{1, 2, 3, 4, 5, 9}, new byte[]{1, 2, 3, 4, 5, 6}));
    }

    @Test
    void method2IgnoresDifferencesAfterSixthByte() {
        // Generated by Codex (gpt-5.4).
        assertTrue(subject.method2(new byte[]{1, 2, 3, 4, 5, 6, 9}, new byte[]{1, 2, 3, 4, 5, 6, 7}));
    }

    @Test
    void method2ThrowsArrayIndexOutOfBoundsExceptionForTooShortArray() {
        // Generated by Codex (gpt-5.4).
        assertThrows(ArrayIndexOutOfBoundsException.class, () -> subject.method2(new byte[]{1, 2, 3, 4, 5}, new byte[]{1, 2, 3, 4, 5, 6}));
    }
}
