package inequivalent;

import org.junit.jupiter.api.Test;

import java.util.Vector;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ClonePair1936Method1Test {

    private final ClonePair1936 subject = new ClonePair1936();

    @Test
    void method1ReturnsTrueForSameReference() {
        // Generated by Codex (gpt-5.4).
        Vector<String> values = new Vector<>();
        values.add("a");

        assertTrue(subject.method1(values, values));
    }

    @Test
    void method1ReturnsFalseForDifferentSizes() {
        // Generated by Codex (gpt-5.4).
        assertFalse(subject.method1(new Vector<>(java.util.List.of("a")), new Vector<>(java.util.List.of("a", "b"))));
    }

    @Test
    void method1IsOrderSensitive() {
        // Generated by Codex (gpt-5.4).
        assertFalse(subject.method1(new Vector<>(java.util.List.of("a", "b")), new Vector<>(java.util.List.of("b", "a"))));
    }

    @Test
    void method1HandlesNullElementsAtSamePosition() {
        // Generated by Codex (gpt-5.4).
        Vector<String> left = new Vector<>();
        left.add(null);
        Vector<String> right = new Vector<>();
        right.add(null);

        assertTrue(subject.method1(left, right));
    }

    @Test
    void method1ThrowsNullPointerExceptionForNullVector() {
        // Generated by Codex (gpt-5.4).
        assertThrows(NullPointerException.class, () -> subject.method1(null, new Vector<>()));
    }
}
