package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair10259DifferenceTest {

    private final ClonePair10259 subject = new ClonePair10259();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertThrowsByName("java.lang.NumberFormatException", () -> subject.method1("\t"));
        assertExpectedSerialized("rO0ABXA=", subject.method2("\t"));
    }
}
