package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair7758DifferenceTest {

    private final ClonePair7758 subject = new ClonePair7758();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbRD6mjBSrY1oeAgAAeHAAAAAA", subject.method1(new byte[]{}));
        assertExpectedSerialized("rO0ABXVyAAJbRgucgYki4AxCAgAAeHAAAAAA", subject.method2(new byte[]{}));
    }
}
