package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair12331DifferenceTest {

    private final ClonePair12331 subject = new ClonePair12331();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertThrowsByName("java.lang.NullPointerException", () -> subject.method1("010", "010", null));
        assertExpectedSerialized("rO0ABXQABG51bGw=", subject.method2("010", "010", null));
    }
}
