package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair12484DifferenceTest {

    private final ClonePair12484 subject = new ClonePair12484();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAA==", subject.method1("\t", false));
        assertExpectedSerialized("rO0ABXQAASA=", subject.method2("\t", false));
    }
}
