package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair11381DifferenceTest {

    private final ClonePair11381 subject = new ClonePair11381();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAzAxMA==", subject.method1("010", "010", "42.0", 0));
        assertExpectedSerialized("rO0ABXQABDQyLjA=", subject.method2("010", "010", "42.0", 0));
    }
}
