package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair10954DifferenceTest {

    private final ClonePair10954 subject = new ClonePair10954();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAzAxMA==", subject.method1("010", 2, ""));
        assertExpectedSerialized("rO0ABXQAAjAx", subject.method2("010", 2, ""));
    }
}
