package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair12911DifferenceTest {

    private final ClonePair12911 subject = new ClonePair12911();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXNyABFqYXZhLmxhbmcuQm9vbGVhbs0gcoDVnPruAgABWgAFdmFsdWV4cAA=", subject.method1(date(0L), null, date(-86_400_000L)));
        assertThrowsByName("java.lang.NullPointerException", () -> subject.method2(date(0L), null, date(-86_400_000L)));
    }
}
