package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair11169DifferenceTest {

    private final ClonePair11169 subject = new ClonePair11169();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXA=", subject.method1(null, null, null));
        assertThrowsByName("java.lang.NullPointerException", () -> subject.method2(null, null, null));
    }
}
