package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair10702DifferenceTest {

    private final ClonePair10702 subject = new ClonePair10702();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAA==", subject.method1("010", "010", null));
        assertExpectedSerialized("rO0ABXQABG51bGw=", subject.method2("010", "010", null));
    }
}
