package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair11258DifferenceTest {

    private final ClonePair11258 subject = new ClonePair11258();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAATQ=", subject.method1("42.0", 1));
        assertExpectedSerialized("rO0ABXQAATA=", subject.method2("42.0", 1));
    }
}
