package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair6672DifferenceTest {

    private final ClonePair6672 subject = new ClonePair6672();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertThrowsByName("java.lang.NullPointerException", () -> subject.method1(list(), null));
        assertExpectedSerialized("rO0ABXQAAA==", subject.method2(list(), null));
    }
}
