package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair6231DifferenceTest {

    private final ClonePair6231 subject = new ClonePair6231();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXNyABFqYXZhLmxhbmcuQm9vbGVhbs0gcoDVnPruAgABWgAFdmFsdWV4cAE=", subject.method1(null, null));
        assertThrowsByName("java.lang.NullPointerException", () -> subject.method2(null, null));
    }
}
