package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair3547DifferenceTest {

    private final ClonePair3547 subject = new ClonePair3547();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbRD6mjBSrY1oeAgAAeHAAAAAB//AAAAAAAAA=", subject.method1(d2(), 1));
        assertExpectedSerialized("rO0ABXVyAAJbRD6mjBSrY1oeAgAAeHAAAAABf+////////8=", subject.method2(d2(), 1));
    }
}
