package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair1846DifferenceTest {

    private final ClonePair1846 subject = new ClonePair1846();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQACmFscGhhIGJldGE=", subject.method1(list("alpha", "beta")));
        assertExpectedSerialized("rO0ABXQAC2FscGhhLCBiZXRh", subject.method2(list("alpha", "beta")));
    }
}
