package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair1695DifferenceTest {

    private final ClonePair1695 subject = new ClonePair1695();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXNyABFqYXZhLmxhbmcuQm9vbGVhbs0gcoDVnPruAgABWgAFdmFsdWV4cAA=", subject.method1(null, null));
        assertExpectedSerialized("rO0ABXNyABFqYXZhLmxhbmcuQm9vbGVhbs0gcoDVnPruAgABWgAFdmFsdWV4cAE=", subject.method2(null, null));
    }
}
