package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair8110DifferenceTest {

    private final ClonePair8110 subject = new ClonePair8110();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAjAx", subject.method1(2, "010"));
        assertExpectedSerialized("rO0ABXQAAjEw", subject.method2(2, "010"));
    }
}
