package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair13125DifferenceTest {

    private final ClonePair13125 subject = new ClonePair13125();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertThrowsByName("java.lang.NumberFormatException", () -> subject.method1("“ "));
        assertThrowsByName("java.lang.StringIndexOutOfBoundsException", () -> subject.method2("“ "));
    }
}
