package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair7857DifferenceTest {

    private final ClonePair7857 subject = new ClonePair7857();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXNyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHD/////", subject.method1(null, 1, 1, '\0'));
        assertThrowsByName("java.lang.NullPointerException", () -> subject.method2(null, 1, 1, '\0'));
    }
}
