package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair11363DifferenceTest {

    private final ClonePair11363 subject = new ClonePair11363();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQABG51bGw=", subject.method1("010", "010", null));
        assertThrowsByName("java.lang.NullPointerException", () -> subject.method2("010", "010", null));
    }
}
