package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair10882DifferenceTest {

    private final ClonePair10882 subject = new ClonePair10882();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAA==", subject.method1("", null, null));
        assertThrowsByName("java.lang.NullPointerException", () -> subject.method2("", null, null));
    }
}
