package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair11462DifferenceTest {

    private final ClonePair11462 subject = new ClonePair11462();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAzAxMA==", subject.method1("010", "010", null));
        assertExpectedSerialized("rO0ABXQAAA==", subject.method2("010", "010", null));
    }
}
