package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair12929DifferenceTest {

    private final ClonePair12929 subject = new ClonePair12929();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbSU26YCZ26rKlAgAAeHAAAAACAAAAAQAAAAQ=", subject.method1(1, 1, 1, new int[]{1, 2}, new int[]{1, 2}));
        assertExpectedSerialized("rO0ABXVyAAJbSU26YCZ26rKlAgAAeHAAAAACAAAAAQAAAAA=", subject.method2(1, 1, 1, new int[]{1, 2}, new int[]{1, 2}));
    }
}
