package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair5507DifferenceTest {

    private final ClonePair5507 subject = new ClonePair5507();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXVyAAJbSU26YCZ26rKlAgAAeHAAAAABAAAAAA==", subject.method1(new int[]{0}, 1));
        assertExpectedSerialized("rO0ABXVyAAJbSU26YCZ26rKlAgAAeHAAAAABAAAAAQ==", subject.method2(new int[]{0}, 1));
    }
}
