package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair3914DifferenceTest {

    private final ClonePair3914 subject = new ClonePair3914();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXNyABBqYXZhLmxhbmcuRG91YmxlgLPCSilr+wQCAAFEAAV2YWx1ZXhyABBqYXZhLmxhbmcuTnVtYmVyhqyVHQuU4IsCAAB4cEAGoJ5mfzvN", subject.method1(new double[]{1.0, 2.0}, new double[]{-1.0, 0.0, 1.0}));
        assertExpectedSerialized("rO0ABXNyABBqYXZhLmxhbmcuRG91YmxlgLPCSilr+wQCAAFEAAV2YWx1ZXhyABBqYXZhLmxhbmcuTnVtYmVyhqyVHQuU4IsCAAB4cEAQAAAAAAAA", subject.method2(new double[]{1.0, 2.0}, new double[]{-1.0, 0.0, 1.0}));
    }
}
