package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair10016DifferenceTest {

    private final ClonePair10016 subject = new ClonePair10016();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAWE=", subject.method1("aaa", "aa", "a"));
        assertExpectedSerialized("rO0ABXQAAmFh", subject.method2("aaa", "aa", "a"));
    }
}
