package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair11252DifferenceTest {

    private final ClonePair11252 subject = new ClonePair11252();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQABzQyLjAwMTA=", subject.method1("010", "", "42.0"));
        assertExpectedSerialized("rO0ABXQABzAxMDQyLjA=", subject.method2("010", "", "42.0"));
    }
}
