package all;

import org.junit.jupiter.api.Test;

import static all.ClonePairDifferenceTestSupport.*;

class ClonePair8276DifferenceTest {

    private final ClonePair8276 subject = new ClonePair8276();

    @Test
    void methodsDivergeOnGeneratedCounterexample() {
        // Generated by Codex (gpt-5.4).
        assertExpectedSerialized("rO0ABXQAAzAtMQ==", subject.method1(-1, 3));
        assertExpectedSerialized("rO0ABXQAAi0x", subject.method2(-1, 3));
    }
}
